// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.


use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone, Default, PartialEq)]
pub struct DisplayLineMeasurement {
    /// FILLER PIC FILLER
    pub _filler_53: FixedString<50>,
    /// FILLER PIC FILLER
    pub _filler_55: FixedString<50>,
    /// FILLER PIC FILLER
    pub _filler_57: FixedString<20>,
}
impl std::fmt::Display for DisplayLineMeasurement {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self._filler_53, self._filler_55, self._filler_57)
    }
}
impl From<&str> for DisplayLineMeasurement {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for DisplayLineMeasurement {
    fn from(_s: String) -> Self { Self::default() }
}
impl DisplayLineMeasurement {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PrintLineMeasurement {
    /// FILLER PIC FILLER
    pub _filler_61: FixedString<51>,
    /// FILLER PIC FILLER
    pub _filler_63: FixedString<50>,
    /// FILLER PIC FILLER
    pub _filler_65: FixedString<32>,
}
impl std::fmt::Display for PrintLineMeasurement {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self._filler_61, self._filler_63, self._filler_65)
    }
}
impl From<&str> for PrintLineMeasurement {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PrintLineMeasurement {
    fn from(_s: String) -> Self { Self::default() }
}
impl PrintLineMeasurement {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct HoldPpsComponents {
    /// H-PYMT-AMT
    pub h_pymt_amt: Decimal /* 7,2 Unsigned */,
    /// H-WAGE-ADJ-PYMT-AMT
    pub h_wage_adj_pymt_amt: Decimal /* 7,2 Unsigned */,
    /// H-FIXED-LOSS-AMT
    pub h_fixed_loss_amt: Decimal /* 7,2 Unsigned */,
    /// H-ESRD-FAC-RATE
    pub h_esrd_fac_rate: Decimal /* 7,2 Unsigned */,
    /// H-PATIENT-AGE
    pub h_patient_age: u32,
    /// H-AGE-FACTOR
    pub h_age_factor: Decimal /* 1,3 Unsigned */,
    /// H-BSA-FACTOR
    pub h_bsa_factor: Decimal /* 1,4 Unsigned */,
    /// H-BMI-FACTOR
    pub h_bmi_factor: Decimal /* 1,4 Unsigned */,
    /// H-BSA
    pub h_bsa: Decimal /* 3,4 Unsigned */,
    /// H-BMI
    pub h_bmi: Decimal /* 3,4 Unsigned */,
    /// H-DRUG-ADDON
    pub h_drug_addon: Decimal /* 1,4 Unsigned */,
}
impl std::fmt::Display for HoldPpsComponents {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}", self.h_pymt_amt, self.h_wage_adj_pymt_amt, self.h_fixed_loss_amt, self.h_esrd_fac_rate, self.h_patient_age, self.h_age_factor, self.h_bsa_factor, self.h_bmi_factor, self.h_bsa, self.h_bmi, self.h_drug_addon)
    }
}
impl From<&str> for HoldPpsComponents {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for HoldPpsComponents {
    fn from(_s: String) -> Self { Self::default() }
}
impl HoldPpsComponents {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BillNewData {
    /// BILL-PORTION
    pub bill_portion: BillPortion,
    /// PROVIDER-SPECIFIC-FILE-PORTION
    pub provider_specific_file_portion: ProviderSpecificFilePortion,
    /// BUNDLED-BILL-PORTION
    pub bundled_bill_portion: BundledBillPortion,
    /// COMORBIDITIES-PORTION
    pub comorbidities_portion: ComorbiditiesPortion,
    /// BILL-DATA-TEST
    pub bill_data_test: BillDataTest,
    /// BUNDLED-TEST-INDIC
    pub bundled_test_indic: FixedString<1>,
}
impl std::fmt::Display for BillNewData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}", self.bill_portion, self.provider_specific_file_portion, self.bundled_bill_portion, self.comorbidities_portion, self.bill_data_test, self.bundled_test_indic)
    }
}
impl From<&str> for BillNewData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BillNewData {
    fn from(_s: String) -> Self { Self::default() }
}
impl BillNewData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BillPortion {
    /// B-COND-CODE
    pub b_cond_code: FixedString<2>,
    /// B-REV-CODE
    pub b_rev_code: BRevCode,
    /// B-PATIENT-HGT
    pub b_patient_hgt: Decimal /* 7,2 Unsigned */,
    /// B-PATIENT-HEIGHT
    pub b_patient_height: u32,
    /// B-PATIENT-WGT
    pub b_patient_wgt: Decimal /* 7,2 Unsigned */,
    /// B-PATIENT-WEIGHT
    pub b_patient_weight: u32,
    /// B-THRU-DATE
    pub b_thru_date: BThruDate,
    /// B-DOB-DATE
    pub b_dob_date: BDobDate,
    /// FILLER PIC FILLER
    pub _filler_173: FixedString<20>,
}
impl std::fmt::Display for BillPortion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}", self.b_cond_code, self.b_rev_code, self.b_patient_hgt, self.b_patient_height, self.b_patient_wgt, self.b_patient_weight, self.b_thru_date, self.b_dob_date, self._filler_173)
    }
}
impl From<&str> for BillPortion {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BillPortion {
    fn from(_s: String) -> Self { Self::default() }
}
impl BillPortion {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BRevCode {
    /// B-REV-CODE3
    pub b_rev_code3: FixedString<3>,
    /// FILLER PIC FILLER
    pub _filler_158: FixedString<1>,
}
impl std::fmt::Display for BRevCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.b_rev_code3, self._filler_158)
    }
}
impl From<&str> for BRevCode {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BRevCode {
    fn from(_s: String) -> Self { Self::default() }
}
impl BRevCode {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BThruDate {
    /// B-THRU-CCYY
    pub b_thru_ccyy: u32,
    /// B-THRU-MM
    pub b_thru_mm: u32,
    /// B-THRU-DD
    pub b_thru_dd: u32,
}
impl std::fmt::Display for BThruDate {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.b_thru_ccyy, self.b_thru_mm, self.b_thru_dd)
    }
}
impl From<&str> for BThruDate {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BThruDate {
    fn from(_s: String) -> Self { Self::default() }
}
impl BThruDate {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BDobDate {
    /// B-DOB-CCYY
    pub b_dob_ccyy: u32,
    /// B-DOB-MM
    pub b_dob_mm: u32,
    /// B-DOB-DD
    pub b_dob_dd: u32,
}
impl std::fmt::Display for BDobDate {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.b_dob_ccyy, self.b_dob_mm, self.b_dob_dd)
    }
}
impl From<&str> for BDobDate {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BDobDate {
    fn from(_s: String) -> Self { Self::default() }
}
impl BDobDate {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ProviderSpecificFilePortion {
    /// P-NPI
    pub p_npi: FixedString<8>,
    /// P-NPI-FILLER
    pub p_npi_filler: FixedString<2>,
    /// P-PROV-OSCAR
    pub p_prov_oscar: FixedString<6>,
    /// P-GEO-MSA
    pub p_geo_msa: FixedString<4>,
    /// P-GEO-CBSA
    pub p_geo_cbsa: FixedString<5>,
    /// P-SPEC-PYMT-IND
    pub p_spec_pymt_ind: FixedString<1>,
    /// P-PROV-TYPE
    pub p_prov_type: FixedString<2>,
    /// P-SPEC-WAGE-INDX
    pub p_spec_wage_indx: Decimal /* 2,4 Unsigned */,
    /// P-ESRD-RATE
    pub p_esrd_rate: Decimal /* 7,2 Unsigned */,
    /// P-PROV-WAIVE-BLEND-PAY-INDIC
    pub p_prov_waive_blend_pay_indic: FixedString<1>,
    /// P-PROV-LOW-VOLUME-INDIC
    pub p_prov_low_volume_indic: FixedString<1>,
    /// P-PACIFIC-IS-TRUST-TERR
    pub p_pacific_is_trust_terr: FixedString<1>,
    /// P-QIP-REDUCTION
    pub p_qip_reduction: FixedString<1>,
    /// P-SUPP-WI-IND
    pub p_supp_wi_ind: FixedString<1>,
    /// P-SUPP-WI
    pub p_supp_wi: Decimal /* 2,4 Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_193: FixedString<8>,
    /// OLD-TEST-INDICATOR
    pub old_test_indicator: FixedString<1>,
    /// FILLER PIC FILLER
    pub _filler_196: FixedString<23>,
}
impl std::fmt::Display for ProviderSpecificFilePortion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self.p_npi, self.p_npi_filler, self.p_prov_oscar, self.p_geo_msa, self.p_geo_cbsa, self.p_spec_pymt_ind, self.p_prov_type, self.p_spec_wage_indx, self.p_esrd_rate, self.p_prov_waive_blend_pay_indic, self.p_prov_low_volume_indic, self.p_pacific_is_trust_terr, self.p_qip_reduction, self.p_supp_wi_ind, self.p_supp_wi, self._filler_193, self.old_test_indicator, self._filler_196)
    }
}
impl From<&str> for ProviderSpecificFilePortion {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ProviderSpecificFilePortion {
    fn from(_s: String) -> Self { Self::default() }
}
impl ProviderSpecificFilePortion {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BundledBillPortion {
    /// B-CLAIM-NUM-DIALYSIS-SESSIONS
    pub b_claim_num_dialysis_sessions: u32,
    /// B-LINE-ITEM-DATE-SERVICE
    pub b_line_item_date_service: BLineItemDateService,
    /// B-DIALYSIS-START-DATE
    pub b_dialysis_start_date: BDialysisStartDate,
    /// B-TOT-PRICE-SB-OUTLIER
    pub b_tot_price_sb_outlier: Decimal /* 7,2 Unsigned */,
    /// B-PAYER-ONLY-VC-Q8
    pub b_payer_only_vc_q8: Decimal /* 7,4 Unsigned */,
    /// B-DATA-CODE
    pub b_data_code: FixedString<2>,
    /// B-PAYER-ONLY-VALUE-CODE
    pub b_payer_only_value_code: FixedString<2>,
    /// B-PAYER-ONLY-VC-QG-AMT
    pub b_payer_only_vc_qg_amt: Decimal /* 7,4 Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_219: FixedString<14>,
}
impl std::fmt::Display for BundledBillPortion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}", self.b_claim_num_dialysis_sessions, self.b_line_item_date_service, self.b_dialysis_start_date, self.b_tot_price_sb_outlier, self.b_payer_only_vc_q8, self.b_data_code, self.b_payer_only_value_code, self.b_payer_only_vc_qg_amt, self._filler_219)
    }
}
impl From<&str> for BundledBillPortion {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BundledBillPortion {
    fn from(_s: String) -> Self { Self::default() }
}
impl BundledBillPortion {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BLineItemDateService {
    /// B-LINE-ITEM-DT-SVC-CCYY
    pub b_line_item_dt_svc_ccyy: u32,
    /// B-LINE-ITEM-DT-SVC-MM
    pub b_line_item_dt_svc_mm: u32,
    /// B-LINE-ITEM-DT-SVC-DD
    pub b_line_item_dt_svc_dd: u32,
}
impl std::fmt::Display for BLineItemDateService {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.b_line_item_dt_svc_ccyy, self.b_line_item_dt_svc_mm, self.b_line_item_dt_svc_dd)
    }
}
impl From<&str> for BLineItemDateService {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BLineItemDateService {
    fn from(_s: String) -> Self { Self::default() }
}
impl BLineItemDateService {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BDialysisStartDate {
    /// B-DIALYSIS-START-DT-CCYY
    pub b_dialysis_start_dt_ccyy: u32,
    /// B-DIALYSIS-START-DT-MM
    pub b_dialysis_start_dt_mm: u32,
    /// B-DIALYSIS-START-DT-DD
    pub b_dialysis_start_dt_dd: u32,
}
impl std::fmt::Display for BDialysisStartDate {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.b_dialysis_start_dt_ccyy, self.b_dialysis_start_dt_mm, self.b_dialysis_start_dt_dd)
    }
}
impl From<&str> for BDialysisStartDate {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BDialysisStartDate {
    fn from(_s: String) -> Self { Self::default() }
}
impl BDialysisStartDate {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ComorbiditiesPortion {
    /// COMORBID-DATA
    pub comorbid_data: [FixedString<2>; 6],
    /// COMORBID-RECURRENCE-COND-CODE
    pub comorbid_recurrence_cond_code: FixedString<2>,
    /// COMORBID-CWF-RETURN-CODE
    pub comorbid_cwf_return_code: FixedString<2>,
}
impl std::fmt::Display for ComorbiditiesPortion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.comorbid_recurrence_cond_code, self.comorbid_cwf_return_code)
    }
}
impl From<&str> for ComorbiditiesPortion {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ComorbiditiesPortion {
    fn from(_s: String) -> Self { Self::default() }
}
impl ComorbiditiesPortion {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BillDataTest {
    /// DRUG-ADD-ON-RETURN
    pub drug_add_on_return: Decimal /* 1,4 Unsigned */,
    /// MSA-WAGE-ADJ
    pub msa_wage_adj: Decimal /* 4,2 Unsigned */,
    /// COMP-CBSA-WAGE-ADJ
    pub comp_cbsa_wage_adj: Decimal /* 4,2 Unsigned */,
    /// CBSA-WAGE-ADJ
    pub cbsa_wage_adj: Decimal /* 4,2 Unsigned */,
    /// BUND-CBSA-WAGE-ADJ
    pub bund_cbsa_wage_adj: Decimal /* 4,2 Unsigned */,
    /// CBSA-WAGE-PMT-RATE
    pub cbsa_wage_pmt_rate: Decimal /* 4,2 Unsigned */,
    /// COND-CD-73
    pub cond_cd_73: CondCd73,
    /// COND-CD-74
    pub cond_cd_74: CondCd74,
    /// AGE-RETURN
    pub age_return: u32,
    /// MSA-WAGE-AMT
    pub msa_wage_amt: Decimal /* 4,2 Signed */,
    /// CBSA-WAGE-INDEX
    pub cbsa_wage_index: Decimal /* 2,4 Signed */,
    /// LABOR-PCT
    pub labor_pct: Decimal /* 1,5 Unsigned */,
    /// PPS-BMI
    pub pps_bmi: Decimal /* 3,4 Unsigned */,
    /// PPS-BSA
    pub pps_bsa: Decimal /* 3,4 Unsigned */,
    /// MSA-PCT
    pub msa_pct: Decimal /* 1,2 Unsigned */,
    /// CBSA-PCT
    pub cbsa_pct: Decimal /* 1,2 Unsigned */,
    /// COM-CBSA-PCT-BLEND
    pub com_cbsa_pct_blend: Decimal /* 1,2 Unsigned */,
    /// BUN-CBSA-PCT-BLEND
    pub bun_cbsa_pct_blend: Decimal /* 1,2 Unsigned */,
    /// CASE-MIX-FCTR-ADJ-RATE
    pub case_mix_fctr_adj_rate: Decimal /* 7,2 Unsigned */,
    /// BUN-BSA
    pub bun_bsa: Decimal /* 3,4 Unsigned */,
    /// BUN-BMI
    pub bun_bmi: Decimal /* 3,4 Unsigned */,
    /// BUN-ONSET-FACTOR
    pub bun_onset_factor: Decimal /* 1,4 Unsigned */,
    /// BUN-COMORBID-MULTIPLIER
    pub bun_comorbid_multiplier: Decimal /* 1,3 Unsigned */,
    /// BUN-WAGE-ADJ-TRAINING-AMT
    pub bun_wage_adj_training_amt: Decimal /* 4,4 Unsigned */,
    /// BUN-LOW-VOL-MULTIPLIER
    pub bun_low_vol_multiplier: Decimal /* 1,3 Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_287: FixedString<18>,
    /// OUT-AGE-FACTOR
    pub out_age_factor: Decimal /* 1,3 Unsigned */,
    /// OUT-BSA
    pub out_bsa: Decimal /* 3,4 Unsigned */,
    /// OUT-BSA-FACTOR
    pub out_bsa_factor: Decimal /* 1,4 Unsigned */,
    /// OUT-BMI
    pub out_bmi: Decimal /* 3,4 Unsigned */,
    /// OUT-BMI-FACTOR
    pub out_bmi_factor: Decimal /* 1,4 Unsigned */,
    /// OUT-ONSET-FACTOR
    pub out_onset_factor: Decimal /* 1,4 Unsigned */,
    /// OUT-COMORBID-MULTIPLIER
    pub out_comorbid_multiplier: Decimal /* 1,3 Unsigned */,
    /// OUT-LOW-VOL-MULTIPLIER
    pub out_low_vol_multiplier: Decimal /* 1,3 Unsigned */,
    /// OUT-ADJ-AVG-MAP-AMT
    pub out_adj_avg_map_amt: Decimal /* 3,2 Unsigned */,
    /// OUT-LOSS-SHARING-PCT
    pub out_loss_sharing_pct: Decimal /* 1,2 Unsigned */,
    /// OUT-IMPUTED-MAP
    pub out_imputed_map: Decimal /* 4,4 Unsigned */,
    /// OUT-FIX-DOLLAR-LOSS
    pub out_fix_dollar_loss: Decimal /* 4,2 Unsigned */,
    /// OUT-PREDICTED-MAP
    pub out_predicted_map: Decimal /* 7,4 Unsigned */,
    /// OUT-PREDICTED-SERVICES-MAP
    pub out_predicted_services_map: Decimal /* 2,4 Unsigned */,
}
impl std::fmt::Display for BillDataTest {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self.drug_add_on_return, self.msa_wage_adj, self.comp_cbsa_wage_adj, self.cbsa_wage_adj, self.bund_cbsa_wage_adj, self.cbsa_wage_pmt_rate, self.cond_cd_73, self.cond_cd_74, self.age_return, self.msa_wage_amt, self.cbsa_wage_index, self.labor_pct, self.pps_bmi, self.pps_bsa, self.msa_pct, self.cbsa_pct, self.com_cbsa_pct_blend, self.bun_cbsa_pct_blend, self.case_mix_fctr_adj_rate, self.bun_bsa, self.bun_bmi, self.bun_onset_factor, self.bun_comorbid_multiplier, self.bun_wage_adj_training_amt, self.bun_low_vol_multiplier, self._filler_287, self.out_age_factor, self.out_bsa, self.out_bsa_factor, self.out_bmi, self.out_bmi_factor, self.out_onset_factor, self.out_comorbid_multiplier, self.out_low_vol_multiplier, self.out_adj_avg_map_amt, self.out_loss_sharing_pct, self.out_imputed_map, self.out_fix_dollar_loss, self.out_predicted_map, self.out_predicted_services_map)
    }
}
impl From<&str> for BillDataTest {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BillDataTest {
    fn from(_s: String) -> Self { Self::default() }
}
impl BillDataTest {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CondCd73 {
    /// FILLER PIC FILLER
    pub _filler_260: FixedString<1>,
    /// AMT-INDIC
    pub amt_indic: FixedString<1>,
    /// FILLER PIC FILLER
    pub _filler_262: FixedString<1>,
    /// BLOOD-DOLLAR
    pub blood_dollar: u32,
    /// FILLER PIC FILLER
    pub _filler_264: FixedString<3>,
}
impl std::fmt::Display for CondCd73 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}", self._filler_260, self.amt_indic, self._filler_262, self.blood_dollar, self._filler_264)
    }
}
impl From<&str> for CondCd73 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CondCd73 {
    fn from(_s: String) -> Self { Self::default() }
}
impl CondCd73 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CondCd74 {
    /// HEMO-CCPD-CAPD
    pub hemo_ccpd_capd: Decimal /* 2,6 Unsigned */,
}
impl std::fmt::Display for CondCd74 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.hemo_ccpd_capd)
    }
}
impl From<&str> for CondCd74 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CondCd74 {
    fn from(_s: String) -> Self { Self::default() }
}
impl CondCd74 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PpsDataAll {
    /// PPS-RTC
    pub pps_rtc: u32,
    /// PPS-DATA
    pub pps_data: PpsData,
    /// PPS-OTHER-DATA
    pub pps_other_data: PpsOtherData,
    /// PPS-BUNDLED-DATA
    pub pps_bundled_data: PpsBundledData,
    /// MSA-ADJ-YEAR-AMT
    pub msa_adj_year_amt: Decimal /* 4,2 Unsigned */,
    /// PPS-LOW-VOL-AMT
    pub pps_low_vol_amt: Decimal /* 4,2 Unsigned */,
    /// OUT-CASE-MIX-PREDICTED-MAP
    pub out_case_mix_predicted_map: Decimal /* 4,4 Unsigned */,
    /// OUT-HEMO-EQUIV-DIAL-SESSIONS
    pub out_hemo_equiv_dial_sessions: Decimal /* 2,4 Unsigned */,
    /// OUT-SB-BSA
    pub out_sb_bsa: Decimal /* 1,3 Unsigned */,
    /// OUT-SB-BMI
    pub out_sb_bmi: Decimal /* 1,3 Unsigned */,
    /// A-49-CENT-DRUG-ADJ
    pub a_49_cent_drug_adj: Decimal /* 1,2 Unsigned */,
    /// PPS-CM-BSA
    pub pps_cm_bsa: Decimal /* 1,3 Unsigned */,
    /// PPS-CM-BMI-LT-18-5
    pub pps_cm_bmi_lt_18_5: Decimal /* 1,3 Unsigned */,
    /// PPS-BUN-BASE-PMT-RATE
    pub pps_bun_base_pmt_rate: Decimal /* 4,2 Unsigned */,
    /// BUN-ADJUSTED-BASE-WAGE-AMT
    pub bun_adjusted_base_wage_amt: Decimal /* 7,4 Unsigned */,
    /// CR-BSA-MULTIPLIER
    pub cr_bsa_multiplier: Decimal /* 1,3 Unsigned */,
    /// CR-BMI-MULTIPLIER
    pub cr_bmi_multiplier: Decimal /* 1,3 Unsigned */,
    /// PPS-BUN-CBSA-W-INDEX
    pub pps_bun_cbsa_w_index: Decimal /* 2,4 Unsigned */,
    /// PPS-BUN-WAGE-ADJ-TRAIN-AMT
    pub pps_bun_wage_adj_train_amt: Decimal /* 7,4 Unsigned */,
    /// PPS-TRAINING-ADD-ON-PMT-AMT
    pub pps_training_add_on_pmt_amt: Decimal /* 2,2 Unsigned */,
    /// OUT-NON-PER-DIEM-PAYMENT
    pub out_non_per_diem_payment: Decimal /* 7,4 Unsigned */,
    /// COM-PAYMENT-RATE
    pub com_payment_rate: Decimal /* 4,2 Unsigned */,
    /// TDAPA-RETURN
    pub tdapa_return: Decimal /* 7,4 Unsigned */,
    /// TPNIES-RETURN
    pub tpnies_return: Decimal /* 7,4 Unsigned */,
    /// NETWORK-REDUCTION-RETURN
    pub network_reduction_return: Decimal /* 1,2 Unsigned */,
    /// ADJ-BASE-WAGE-BEFORE-ETC-HDPA
    pub adj_base_wage_before_etc_hdpa: Decimal /* 7,4 Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_391: FixedString<66>,
}
impl std::fmt::Display for PpsDataAll {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self.pps_rtc, self.pps_data, self.pps_other_data, self.pps_bundled_data, self.msa_adj_year_amt, self.pps_low_vol_amt, self.out_case_mix_predicted_map, self.out_hemo_equiv_dial_sessions, self.out_sb_bsa, self.out_sb_bmi, self.a_49_cent_drug_adj, self.pps_cm_bsa, self.pps_cm_bmi_lt_18_5, self.pps_bun_base_pmt_rate, self.bun_adjusted_base_wage_amt, self.cr_bsa_multiplier, self.cr_bmi_multiplier, self.pps_bun_cbsa_w_index, self.pps_bun_wage_adj_train_amt, self.pps_training_add_on_pmt_amt, self.out_non_per_diem_payment, self.com_payment_rate, self.tdapa_return, self.tpnies_return, self.network_reduction_return, self.adj_base_wage_before_etc_hdpa, self._filler_391)
    }
}
impl From<&str> for PpsDataAll {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PpsDataAll {
    fn from(_s: String) -> Self { Self::default() }
}
impl PpsDataAll {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PpsData {
    /// PPS-MSA
    pub pps_msa: FixedString<4>,
    /// PPS-CBSA
    pub pps_cbsa: FixedString<5>,
    /// PPS-WAGE-ADJ-RATE
    pub pps_wage_adj_rate: Decimal /* 4,2 Unsigned */,
    /// PPS-FINAL-PAY-AMT
    pub pps_final_pay_amt: Decimal /* 7,2 Unsigned */,
    /// PPS-CALC-VERS-CD
    pub pps_calc_vers_cd: FixedString<5>,
    /// PPS-COND-CODE
    pub pps_cond_code: FixedString<2>,
    /// PPS-REV-CODE
    pub pps_rev_code: FixedString<4>,
    /// PPS-2011-WAGE-ADJ-RATE
    pub pps_2011_wage_adj_rate: Decimal /* 4,2 Unsigned */,
    /// PPS-2011-NAT-LABOR-PCT
    pub pps_2011_nat_labor_pct: Decimal /* 1,5 Unsigned */,
    /// PPS-2011-NAT-NONLABOR-PCT
    pub pps_2011_nat_nonlabor_pct: Decimal /* 1,5 Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_330: FixedString<2>,
}
impl std::fmt::Display for PpsData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}", self.pps_msa, self.pps_cbsa, self.pps_wage_adj_rate, self.pps_final_pay_amt, self.pps_calc_vers_cd, self.pps_cond_code, self.pps_rev_code, self.pps_2011_wage_adj_rate, self.pps_2011_nat_labor_pct, self.pps_2011_nat_nonlabor_pct, self._filler_330)
    }
}
impl From<&str> for PpsData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PpsData {
    fn from(_s: String) -> Self { Self::default() }
}
impl PpsData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PpsOtherData {
    /// PPS-NAT-LABOR-PCT
    pub pps_nat_labor_pct: Decimal /* 1,5 Unsigned */,
    /// PPS-NAT-NONLABOR-PCT
    pub pps_nat_nonlabor_pct: Decimal /* 1,5 Unsigned */,
    /// PPS-AGE-FACTOR
    pub pps_age_factor: Decimal /* 1,3 Unsigned */,
    /// PPS-BSA-FACTOR
    pub pps_bsa_factor: Decimal /* 1,4 Unsigned */,
    /// PPS-BMI-FACTOR
    pub pps_bmi_factor: Decimal /* 1,4 Unsigned */,
    /// PPS-BDGT-NEUT-RATE
    pub pps_bdgt_neut_rate: Decimal /* 1,4 Unsigned */,
    /// PPS-2011-AGE-FACTOR
    pub pps_2011_age_factor: Decimal /* 1,3 Unsigned */,
    /// PPS-2011-BSA-FACTOR
    pub pps_2011_bsa_factor: Decimal /* 1,4 Unsigned */,
    /// PPS-2011-BMI-FACTOR
    pub pps_2011_bmi_factor: Decimal /* 1,4 Unsigned */,
    /// PPS-2011-BDGT-NEUT-RATE
    pub pps_2011_bdgt_neut_rate: Decimal /* 1,4 Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_343: FixedString<1>,
}
impl std::fmt::Display for PpsOtherData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}", self.pps_nat_labor_pct, self.pps_nat_nonlabor_pct, self.pps_age_factor, self.pps_bsa_factor, self.pps_bmi_factor, self.pps_bdgt_neut_rate, self.pps_2011_age_factor, self.pps_2011_bsa_factor, self.pps_2011_bmi_factor, self.pps_2011_bdgt_neut_rate, self._filler_343)
    }
}
impl From<&str> for PpsOtherData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PpsOtherData {
    fn from(_s: String) -> Self { Self::default() }
}
impl PpsOtherData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PpsBundledData {
    /// PPS-2011-COMORBID-DATA
    pub pps_2011_comorbid_data: Pps2011ComorbidData,
    /// PPS-2011-FULL-COMP-RATE
    pub pps_2011_full_comp_rate: Decimal /* 7,2 Unsigned */,
    /// PPS-2011-BLEND-COMP-RATE
    pub pps_2011_blend_comp_rate: Decimal /* 7,2 Unsigned */,
    /// PPS-2011-FULL-PPS-RATE
    pub pps_2011_full_pps_rate: Decimal /* 7,2 Unsigned */,
    /// PPS-2011-BLEND-PPS-RATE
    pub pps_2011_blend_pps_rate: Decimal /* 7,2 Unsigned */,
    /// PPS-2011-FULL-OUTLIER-RATE
    pub pps_2011_full_outlier_rate: Decimal /* 7,2 Unsigned */,
    /// PPS-2011-BLEND-OUTLIER-RATE
    pub pps_2011_blend_outlier_rate: Decimal /* 7,2 Unsigned */,
}
impl std::fmt::Display for PpsBundledData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}", self.pps_2011_comorbid_data, self.pps_2011_full_comp_rate, self.pps_2011_blend_comp_rate, self.pps_2011_full_pps_rate, self.pps_2011_blend_pps_rate, self.pps_2011_full_outlier_rate, self.pps_2011_blend_outlier_rate)
    }
}
impl From<&str> for PpsBundledData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PpsBundledData {
    fn from(_s: String) -> Self { Self::default() }
}
impl PpsBundledData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Pps2011ComorbidData {
    /// PPS-2011-COMORBID-MA
    pub pps_2011_comorbid_ma: FixedString<2>,
    /// PPS-2011-COMORBID-MA-CC
    pub pps_2011_comorbid_ma_cc: FixedString<2>,
    /// PPS-2011-COMORBID-PAY
    pub pps_2011_comorbid_pay: FixedString<2>,
    /// FILLER PIC FILLER
    pub _filler_352: FixedString<24>,
}
impl std::fmt::Display for Pps2011ComorbidData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.pps_2011_comorbid_ma, self.pps_2011_comorbid_ma_cc, self.pps_2011_comorbid_pay, self._filler_352)
    }
}
impl From<&str> for Pps2011ComorbidData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Pps2011ComorbidData {
    fn from(_s: String) -> Self { Self::default() }
}
impl Pps2011ComorbidData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WageNewRateRecord {
    /// W-NEW-MSA
    pub w_new_msa: u32,
    /// W-NEW-EFF-DATE
    pub w_new_eff_date: WNewEffDate,
    /// W-NEW-RATE1-RECORD
    pub w_new_rate1_record: Decimal /* 4,2 Signed */,
    /// W-NEW-RATE2-RECORD
    pub w_new_rate2_record: Decimal /* 4,2 Signed */,
}
impl std::fmt::Display for WageNewRateRecord {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.w_new_msa, self.w_new_eff_date, self.w_new_rate1_record, self.w_new_rate2_record)
    }
}
impl From<&str> for WageNewRateRecord {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WageNewRateRecord {
    fn from(_s: String) -> Self { Self::default() }
}
impl WageNewRateRecord {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WNewEffDate {
    /// W-NEW-EFF-DATE-CC
    pub w_new_eff_date_cc: u32,
    /// W-NEW-EFF-DATE-YMD
    pub w_new_eff_date_ymd: WNewEffDateYmd,
}
impl std::fmt::Display for WNewEffDate {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.w_new_eff_date_cc, self.w_new_eff_date_ymd)
    }
}
impl From<&str> for WNewEffDate {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WNewEffDate {
    fn from(_s: String) -> Self { Self::default() }
}
impl WNewEffDate {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WNewEffDateYmd {
    /// W-NEW-EFF-DATE-YY
    pub w_new_eff_date_yy: u32,
    /// W-NEW-EFF-DATE-MM
    pub w_new_eff_date_mm: u32,
    /// W-NEW-EFF-DATE-DD
    pub w_new_eff_date_dd: u32,
}
impl std::fmt::Display for WNewEffDateYmd {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.w_new_eff_date_yy, self.w_new_eff_date_mm, self.w_new_eff_date_dd)
    }
}
impl From<&str> for WNewEffDateYmd {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WNewEffDateYmd {
    fn from(_s: String) -> Self { Self::default() }
}
impl WNewEffDateYmd {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ComCbsaWageRecord {
    /// COM-CBSA
    pub com_cbsa: u32,
    /// COM-CBSA-DATE
    pub com_cbsa_date: ComCbsaDate,
    /// COM-CBSA-W-INDEX
    pub com_cbsa_w_index: Decimal /* 2,4 Signed */,
}
impl std::fmt::Display for ComCbsaWageRecord {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.com_cbsa, self.com_cbsa_date, self.com_cbsa_w_index)
    }
}
impl From<&str> for ComCbsaWageRecord {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ComCbsaWageRecord {
    fn from(_s: String) -> Self { Self::default() }
}
impl ComCbsaWageRecord {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ComCbsaDate {
    /// COM-CBSA-DATE-CC
    pub com_cbsa_date_cc: u32,
    /// COM-CBSA-DATE-YMD
    pub com_cbsa_date_ymd: ComCbsaDateYmd,
}
impl std::fmt::Display for ComCbsaDate {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.com_cbsa_date_cc, self.com_cbsa_date_ymd)
    }
}
impl From<&str> for ComCbsaDate {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ComCbsaDate {
    fn from(_s: String) -> Self { Self::default() }
}
impl ComCbsaDate {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ComCbsaDateYmd {
    /// COM-CBSA-DATE-YY
    pub com_cbsa_date_yy: u32,
    /// COM-CBSA-DATE-MM
    pub com_cbsa_date_mm: u32,
    /// COM-CBSA-DATE-DD
    pub com_cbsa_date_dd: u32,
}
impl std::fmt::Display for ComCbsaDateYmd {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.com_cbsa_date_yy, self.com_cbsa_date_mm, self.com_cbsa_date_dd)
    }
}
impl From<&str> for ComCbsaDateYmd {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ComCbsaDateYmd {
    fn from(_s: String) -> Self { Self::default() }
}
impl ComCbsaDateYmd {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BunCbsaWageRecord {
    /// BUN-CBSA
    pub bun_cbsa: u32,
    /// BUN-CBSA-DATE
    pub bun_cbsa_date: BunCbsaDate,
    /// BUN-CBSA-W-INDEX
    pub bun_cbsa_w_index: Decimal /* 2,4 Signed */,
}
impl std::fmt::Display for BunCbsaWageRecord {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.bun_cbsa, self.bun_cbsa_date, self.bun_cbsa_w_index)
    }
}
impl From<&str> for BunCbsaWageRecord {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BunCbsaWageRecord {
    fn from(_s: String) -> Self { Self::default() }
}
impl BunCbsaWageRecord {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BunCbsaDate {
    /// BUN-CBSA-DATE-CC
    pub bun_cbsa_date_cc: u32,
    /// BUN-CBSA-DATE-YMD
    pub bun_cbsa_date_ymd: BunCbsaDateYmd,
}
impl std::fmt::Display for BunCbsaDate {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.bun_cbsa_date_cc, self.bun_cbsa_date_ymd)
    }
}
impl From<&str> for BunCbsaDate {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BunCbsaDate {
    fn from(_s: String) -> Self { Self::default() }
}
impl BunCbsaDate {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BunCbsaDateYmd {
    /// BUN-CBSA-DATE-YY
    pub bun_cbsa_date_yy: u32,
    /// BUN-CBSA-DATE-MM
    pub bun_cbsa_date_mm: u32,
    /// BUN-CBSA-DATE-DD
    pub bun_cbsa_date_dd: u32,
}
impl std::fmt::Display for BunCbsaDateYmd {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.bun_cbsa_date_yy, self.bun_cbsa_date_mm, self.bun_cbsa_date_dd)
    }
}
impl From<&str> for BunCbsaDateYmd {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BunCbsaDateYmd {
    fn from(_s: String) -> Self { Self::default() }
}
impl BunCbsaDateYmd {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// W-STORAGE-REF
    pub w_storage_ref: FixedString<46>,
    /// CAL-VERSION
    pub cal_version: FixedString<5>,
    /// DISPLAY-LINE-MEASUREMENT
    pub display_line_measurement: DisplayLineMeasurement,
    /// PRINT-LINE-MEASUREMENT
    pub print_line_measurement: PrintLineMeasurement,
    /// HOLD-PPS-COMPONENTS
    pub hold_pps_components: HoldPpsComponents,
    /// H-PYMT-AMT
    pub h_pymt_amt: Decimal /* 7,2 Unsigned */,
    /// H-WAGE-ADJ-PYMT-AMT
    pub h_wage_adj_pymt_amt: Decimal /* 7,2 Unsigned */,
    /// H-FIXED-LOSS-AMT
    pub h_fixed_loss_amt: Decimal /* 7,2 Unsigned */,
    /// H-ESRD-FAC-RATE
    pub h_esrd_fac_rate: Decimal /* 7,2 Unsigned */,
    /// H-PATIENT-AGE
    pub h_patient_age: u32,
    /// H-AGE-FACTOR
    pub h_age_factor: Decimal /* 1,3 Unsigned */,
    /// H-BSA-FACTOR
    pub h_bsa_factor: Decimal /* 1,4 Unsigned */,
    /// H-BMI-FACTOR
    pub h_bmi_factor: Decimal /* 1,4 Unsigned */,
    /// H-BSA
    pub h_bsa: Decimal /* 3,4 Unsigned */,
    /// H-BMI
    pub h_bmi: Decimal /* 3,4 Unsigned */,
    /// H-DRUG-ADDON
    pub h_drug_addon: Decimal /* 1,4 Unsigned */,
    /// DRUG-ADDON
    pub drug_addon: Decimal /* 1,4 Unsigned */,
    /// MSA-BLEND-PCT
    pub msa_blend_pct: Decimal /* 1,2 Unsigned */,
    /// CBSA-BLEND-PCT
    pub cbsa_blend_pct: Decimal /* 1,2 Unsigned */,
    /// NAT-LABOR-PCT
    pub nat_labor_pct: Decimal /* 1,5 Unsigned */,
    /// NAT-NONLABOR-PCT
    pub nat_nonlabor_pct: Decimal /* 1,5 Unsigned */,
    /// HEMO-PERI-CCPD-AMT
    pub hemo_peri_ccpd_amt: u32,
    /// CAPD-AMT
    pub capd_amt: u32,
    /// CAPD-OR-CCPD-FACTOR
    pub capd_or_ccpd_factor: Decimal /* 1,6 Unsigned */,
    /// CASE-MIX-BDGT-NEUT-FACTOR
    pub case_mix_bdgt_neut_factor: Decimal /* 1,4 Unsigned */,
    /// LINKAGE: BILL-NEW-DATA
    pub bill_new_data: BillNewData,
    /// LINKAGE: PPS-DATA-ALL
    pub pps_data_all: PpsDataAll,
    /// LINKAGE: WAGE-NEW-RATE-RECORD
    pub wage_new_rate_record: WageNewRateRecord,
    /// LINKAGE: COM-CBSA-WAGE-RECORD
    pub com_cbsa_wage_record: ComCbsaWageRecord,
    /// LINKAGE: BUN-CBSA-WAGE-RECORD
    pub bun_cbsa_wage_record: BunCbsaWageRecord,
    /// INDEXED BY COMORBID-INDEX
    pub comorbid_index: u32,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            w_storage_ref: FixedString::from_str("ESCAL056      - W O R K I N G   S T O R A G E"),
            cal_version: FixedString::from_str("C05.6"),
            display_line_measurement: Default::default(),
            print_line_measurement: Default::default(),
            hold_pps_components: Default::default(),
            h_pymt_amt: Default::default(),
            h_wage_adj_pymt_amt: Default::default(),
            h_fixed_loss_amt: Default::default(),
            h_esrd_fac_rate: Default::default(),
            h_patient_age: Default::default(),
            h_age_factor: Default::default(),
            h_bsa_factor: Default::default(),
            h_bmi_factor: Default::default(),
            h_bsa: Default::default(),
            h_bmi: Default::default(),
            h_drug_addon: Default::default(),
            drug_addon: Default::default(),
            msa_blend_pct: Default::default(),
            cbsa_blend_pct: Decimal::from(0f64),
            nat_labor_pct: Decimal::from(0.53711f64),
            nat_nonlabor_pct: Decimal::from(0.46289f64),
            hemo_peri_ccpd_amt: 0,
            capd_amt: 0,
            capd_or_ccpd_factor: Decimal::from(0.428571f64),
            case_mix_bdgt_neut_factor: Decimal::from(0.9116f64),
            bill_new_data: Default::default(),
            pps_data_all: Default::default(),
            wage_new_rate_record: Default::default(),
            com_cbsa_wage_record: Default::default(),
            bun_cbsa_wage_record: Default::default(),
            comorbid_index: 1,
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// WAGE-NEW-RATE-RECORD
fn p_wage_new_rate_record(state: &mut ProgramState) {
}

/// 0000-MAINLINE-CONTROL
fn p_0000_mainline_control(state: &mut ProgramState) {
    p_0100_initial_routine(state);
    if state.pps_data_all.pps_rtc == 00 {
        p_1000_edit_the_bill_info(state);
    }
    if state.pps_data_all.pps_rtc == 00 {
        p_2000_assemble_pps_variables(state);
        p_3000_calc_payment(state);
    }
    p_9000_move_results(state);
    return;
}

/// 0100-INITIAL-ROUTINE
fn p_0100_initial_routine(state: &mut ProgramState) {
    state.pps_data_all = Default::default();
    state.bill_new_data.bill_data_test = Default::default();
    state.hold_pps_components = Default::default();
    state.pps_data_all.pps_rtc = 0;
    state.pps_data_all.pps_data.pps_calc_vers_cd = FixedString::copy_from(&state.cal_version);
    if &format!("{}", state.bill_new_data.provider_specific_file_portion.p_prov_type) == &"40".to_string() {
        state.pps_data_all.pps_other_data.pps_nat_labor_pct = Decimal::from(0i64);
        state.pps_data_all.pps_other_data.pps_nat_nonlabor_pct = Decimal::from(0i64);
        state.pps_data_all.pps_data.pps_wage_adj_rate = Decimal::from_i64(state.wage_new_rate_record.w_new_rate1_record.value, state.wage_new_rate_record.w_new_rate1_record.scale);
        state.bill_new_data.bill_data_test.msa_wage_amt = Decimal::from_i64(state.wage_new_rate_record.w_new_rate1_record.value, state.wage_new_rate_record.w_new_rate1_record.scale);
    } else {
        if &format!("{}", state.bill_new_data.provider_specific_file_portion.p_prov_type) == &"41".to_string() {
            state.pps_data_all.pps_other_data.pps_nat_labor_pct = Decimal::from(0i64);
            state.pps_data_all.pps_other_data.pps_nat_nonlabor_pct = Decimal::from(0i64);
            state.pps_data_all.pps_data.pps_wage_adj_rate = Decimal::from_i64(state.wage_new_rate_record.w_new_rate2_record.value, state.wage_new_rate_record.w_new_rate2_record.scale);
            state.bill_new_data.bill_data_test.msa_wage_amt = Decimal::from_i64(state.wage_new_rate_record.w_new_rate2_record.value, state.wage_new_rate_record.w_new_rate2_record.scale);
        } else {
            state.pps_data_all.pps_rtc = 52 as u32;
            state.pps_data_all.pps_data.pps_wage_adj_rate = Decimal::from(0i64);
        }
    }
    state.pps_data_all.msa_adj_year_amt = Decimal::from_i64(state.pps_data_all.pps_data.pps_wage_adj_rate.value, state.pps_data_all.pps_data.pps_wage_adj_rate.scale);
    state.pps_data_all.pps_other_data.pps_bdgt_neut_rate = Decimal::from_i64(state.case_mix_bdgt_neut_factor.value, state.case_mix_bdgt_neut_factor.scale);
    state.hold_pps_components.h_drug_addon = Decimal::from_i64(state.drug_addon.value, state.drug_addon.scale);
}

/// 1000-EDIT-THE-BILL-INFO
fn p_1000_edit_the_bill_info(state: &mut ProgramState) {
    if state.pps_data_all.pps_rtc == 00 {
        // SKIP: unresolved condition
    }
    if state.pps_data_all.pps_rtc == 00 {
        // SKIP: unresolved condition
    }
    state.pps_data_all.pps_rtc = 54 as u32;
    if state.pps_data_all.pps_rtc == 00 {
        // SKIP: unresolved condition
    }
    state.pps_data_all.pps_rtc = 55 as u32;
    if state.pps_data_all.pps_rtc == 00 {
        // SKIP: unresolved condition
    }
    state.pps_data_all.pps_rtc = 56 as u32;
    if state.pps_data_all.pps_rtc == 00 {
        // SKIP: unresolved condition
    } else {
        state.pps_data_all.pps_rtc = 57 as u32;
    }
    if state.pps_data_all.pps_rtc == 00 {
        // SKIP: unresolved condition
    }
    if state.pps_data_all.pps_rtc == 00 {
        if (i64::from(state.bill_new_data.bill_portion.b_patient_hgt) as f64) > 300.00f64 {
            state.pps_data_all.pps_rtc = 71 as u32;
        }
    }
    if state.pps_data_all.pps_rtc == 00 {
        if (i64::from(state.bill_new_data.bill_portion.b_patient_wgt) as f64) > 500.00f64 {
            state.pps_data_all.pps_rtc = 72 as u32;
        }
    }
    if state.pps_data_all.pps_rtc == 00 {
        p_1200_calc_age(state);
    }
}

/// 1200-CALC-AGE
fn p_1200_calc_age(state: &mut ProgramState) {
    state.hold_pps_components.h_patient_age = (state.bill_new_data.bill_portion.b_thru_date.b_thru_ccyy - state.bill_new_data.bill_portion.b_dob_date.b_dob_ccyy) as u32;
    if state.bill_new_data.bill_portion.b_dob_date.b_dob_mm > state.bill_new_data.bill_portion.b_thru_date.b_thru_mm {
        state.hold_pps_components.h_patient_age = (state.hold_pps_components.h_patient_age as i64 - 1 as i64) as u32;
    }
    if state.hold_pps_components.h_patient_age < 18 {
    }
    if (state.hold_pps_components.h_patient_age > 17) && (state.hold_pps_components.h_patient_age < 45) {
    }
    if (state.hold_pps_components.h_patient_age > 44) && (state.hold_pps_components.h_patient_age < 60) {
    }
    if (state.hold_pps_components.h_patient_age > 59) && (state.hold_pps_components.h_patient_age < 70) {
    }
    if (state.hold_pps_components.h_patient_age > 69) && (state.hold_pps_components.h_patient_age < 80) {
    }
    if state.hold_pps_components.h_patient_age > 79 {
    }
}

/// 2000-ASSEMBLE-PPS-VARIABLES
fn p_2000_assemble_pps_variables(state: &mut ProgramState) {
    state.hold_pps_components.h_wage_adj_pymt_amt = Decimal::from_i64(state.pps_data_all.pps_data.pps_wage_adj_rate.value, state.pps_data_all.pps_data.pps_wage_adj_rate.scale);
    state.hold_pps_components.h_bsa = Decimal::from(((0i64)) as i64);
    state.hold_pps_components.h_bmi = Decimal::from(i64::from((state.bill_new_data.bill_portion.b_patient_wgt / (state.bill_new_data.bill_portion.b_patient_hgt.pow(2))) * 10000));
    if state.hold_pps_components.h_patient_age > 17 {
        state.hold_pps_components.h_bsa_factor = Decimal::from((1) as i64);
    }
    // SKIP: unresolved condition
}

/// 3000-CALC-PAYMENT
fn p_3000_calc_payment(state: &mut ProgramState) {
    state.hold_pps_components.h_pymt_amt = Decimal::from(i64::from(state.hold_pps_components.h_wage_adj_pymt_amt * state.hold_pps_components.h_bmi_factor * state.hold_pps_components.h_bsa_factor * state.pps_data_all.pps_other_data.pps_bdgt_neut_rate * state.hold_pps_components.h_age_factor * state.hold_pps_components.h_drug_addon));
    state.bill_new_data.bill_data_test.case_mix_fctr_adj_rate = Decimal::from_i64(state.hold_pps_components.h_pymt_amt.value, state.hold_pps_components.h_pymt_amt.scale);
    state.bill_new_data.bill_data_test.cond_cd_73 = Default::default();
    // SKIP: unresolved condition
    state.hold_pps_components.h_pymt_amt = Decimal::from(i64::from(state.hold_pps_components.h_pymt_amt + state.hemo_peri_ccpd_amt));
    state.bill_new_data.bill_data_test.cond_cd_73.amt_indic = "A".into();
    state.bill_new_data.bill_data_test.cond_cd_73.blood_dollar = state.hemo_peri_ccpd_amt as u32;
    // SKIP: unresolved condition
    state.hold_pps_components.h_pymt_amt = Decimal::from(i64::from(state.hold_pps_components.h_pymt_amt + state.capd_amt));
    state.bill_new_data.bill_data_test.cond_cd_73.amt_indic = "A".into();
    state.bill_new_data.bill_data_test.cond_cd_73.blood_dollar = state.capd_amt as u32;
    // SKIP: unresolved condition
    state.hold_pps_components.h_pymt_amt = Decimal::from(i64::from(state.hold_pps_components.h_pymt_amt * state.capd_or_ccpd_factor));
    state.bill_new_data.bill_data_test.cond_cd_74.hemo_ccpd_capd = Decimal::from_i64(state.capd_or_ccpd_factor.value, state.capd_or_ccpd_factor.scale);
    state.bill_new_data.bill_data_test.cond_cd_73.amt_indic = "A".into();
    state.bill_new_data.bill_data_test.cond_cd_73.blood_dollar = 0;
    state.pps_data_all.pps_data.pps_final_pay_amt = Decimal::from_i64(state.hold_pps_components.h_pymt_amt.value, state.hold_pps_components.h_pymt_amt.scale);
    state.pps_data_all.pps_data.pps_wage_adj_rate = Decimal::from(0i64);
}

/// 9000-MOVE-RESULTS
fn p_9000_move_results(state: &mut ProgramState) {
    if state.pps_data_all.pps_rtc < 50 {
        state.pps_data_all.pps_data.pps_cond_code = FixedString::copy_from(&state.bill_new_data.bill_portion.b_cond_code);
        state.pps_data_all.pps_data.pps_rev_code = FixedString::copy_from(&state.bill_new_data.bill_portion.b_rev_code);
        state.pps_data_all.pps_data.pps_msa = FixedString::copy_from(&state.bill_new_data.provider_specific_file_portion.p_geo_msa);
        state.pps_data_all.pps_data.pps_cbsa = FixedString::copy_from(&state.bill_new_data.provider_specific_file_portion.p_geo_cbsa);
        state.pps_data_all.pps_other_data.pps_age_factor = Decimal::from_i64(state.hold_pps_components.h_age_factor.value, state.hold_pps_components.h_age_factor.scale);
        state.pps_data_all.pps_other_data.pps_bsa_factor = Decimal::from_i64(state.hold_pps_components.h_bsa_factor.value, state.hold_pps_components.h_bsa_factor.scale);
        state.pps_data_all.pps_other_data.pps_bmi_factor = Decimal::from_i64(state.hold_pps_components.h_bmi_factor.value, state.hold_pps_components.h_bmi_factor.scale);
        // SKIP: unresolved condition
    } else {
        // SKIP: unresolved condition
    }
}

fn main() {
    let mut state = ProgramState::default();
    p_wage_new_rate_record(&mut state);
}

