// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.


use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone, Default, PartialEq)]
pub struct SearchMsaLugar {
    /// SEARCH-MSA
    pub search_msa: SearchMsa,
    /// SEARCH-LUGAR
    pub search_lugar: FixedString<1>,
}
impl std::fmt::Display for SearchMsaLugar {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.search_msa, self.search_lugar)
    }
}
impl From<&str> for SearchMsaLugar {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for SearchMsaLugar {
    fn from(_s: String) -> Self { Self::default() }
}
impl SearchMsaLugar {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SearchMsa {
    /// SEARCH-MSA-POS12
    pub search_msa_pos12: u32,
    /// SEARCH-MSA-POS34
    pub search_msa_pos34: u32,
}
impl std::fmt::Display for SearchMsa {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.search_msa_pos12, self.search_msa_pos34)
    }
}
impl From<&str> for SearchMsa {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for SearchMsa {
    fn from(_s: String) -> Self { Self::default() }
}
impl SearchMsa {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SearchCbsa {
    /// SEARCH-CBSA-POS123
    pub search_cbsa_pos123: u32,
    /// SEARCH-CBSA-POS45
    pub search_cbsa_pos45: u32,
}
impl std::fmt::Display for SearchCbsa {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.search_cbsa_pos123, self.search_cbsa_pos45)
    }
}
impl From<&str> for SearchCbsa {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for SearchCbsa {
    fn from(_s: String) -> Self { Self::default() }
}
impl SearchCbsa {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Ut1Stat {
    /// UT1-STAT1
    pub ut1_stat1: FixedString<1>,
    /// UT1-STAT2
    pub ut1_stat2: FixedString<1>,
}
impl std::fmt::Display for Ut1Stat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.ut1_stat1, self.ut1_stat2)
    }
}
impl From<&str> for Ut1Stat {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Ut1Stat {
    fn from(_s: String) -> Self { Self::default() }
}
impl Ut1Stat {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Ut2Stat {
    /// UT2-STAT1
    pub ut2_stat1: FixedString<1>,
    /// UT2-STAT2
    pub ut2_stat2: FixedString<1>,
}
impl std::fmt::Display for Ut2Stat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.ut2_stat1, self.ut2_stat2)
    }
}
impl From<&str> for Ut2Stat {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Ut2Stat {
    fn from(_s: String) -> Self { Self::default() }
}
impl Ut2Stat {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Ut3Stat {
    /// UT3-STAT1
    pub ut3_stat1: FixedString<1>,
    /// UT3-STAT2
    pub ut3_stat2: FixedString<1>,
}
impl std::fmt::Display for Ut3Stat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.ut3_stat1, self.ut3_stat2)
    }
}
impl From<&str> for Ut3Stat {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Ut3Stat {
    fn from(_s: String) -> Self { Self::default() }
}
impl Ut3Stat {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Ut4Stat {
    /// UT4-STAT1
    pub ut4_stat1: FixedString<1>,
    /// UT4-STAT2
    pub ut4_stat2: FixedString<1>,
}
impl std::fmt::Display for Ut4Stat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.ut4_stat1, self.ut4_stat2)
    }
}
impl From<&str> for Ut4Stat {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Ut4Stat {
    fn from(_s: String) -> Self { Self::default() }
}
impl Ut4Stat {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Ut5Stat {
    /// UT5-STAT1
    pub ut5_stat1: FixedString<1>,
    /// UT5-STAT2
    pub ut5_stat2: FixedString<1>,
}
impl std::fmt::Display for Ut5Stat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.ut5_stat1, self.ut5_stat2)
    }
}
impl From<&str> for Ut5Stat {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Ut5Stat {
    fn from(_s: String) -> Self { Self::default() }
}
impl Ut5Stat {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ProvNewHold {
    /// PROV-NEWREC-HOLD1
    pub prov_newrec_hold1: ProvNewrecHold1,
    /// PROV-NEWREC-HOLD2
    pub prov_newrec_hold2: ProvNewrecHold2,
    /// PROV-NEWREC-HOLD3
    pub prov_newrec_hold3: ProvNewrecHold3,
}
impl std::fmt::Display for ProvNewHold {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.prov_newrec_hold1, self.prov_newrec_hold2, self.prov_newrec_hold3)
    }
}
impl From<&str> for ProvNewHold {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ProvNewHold {
    fn from(_s: String) -> Self { Self::default() }
}
impl ProvNewHold {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ProvNewrecHold1 {
    /// P-NEW-NPI10
    pub p_new_npi10: PNewNpi10,
    /// P-NEW-PROVIDER-NO
    pub p_new_provider_no: PNewProviderNo,
    /// P-NEW-DATE-DATA
    pub p_new_date_data: PNewDateData,
    /// P-NEW-WAIVER-CODE
    pub p_new_waiver_code: FixedString<1>,
    /// P-NEW-INTER-NO
    pub p_new_inter_no: u32,
    /// P-NEW-PROVIDER-TYPE
    pub p_new_provider_type: FixedString<2>,
    /// P-NEW-CURRENT-CENSUS-DIV
    pub p_new_current_census_div: u32,
    /// P-NEW-CURRENT-DIV
    pub p_new_current_div: u32,
    /// P-NEW-MSA-DATA
    pub p_new_msa_data: PNewMsaData,
    /// P-NEW-SOL-COM-DEP-HOSP-YR
    pub p_new_sol_com_dep_hosp_yr: FixedString<2>,
    /// P-NEW-LUGAR
    pub p_new_lugar: FixedString<1>,
    /// P-NEW-TEMP-RELIEF-IND
    pub p_new_temp_relief_ind: FixedString<1>,
    /// P-NEW-FED-PPS-BLEND-IND
    pub p_new_fed_pps_blend_ind: FixedString<1>,
    /// FILLER PIC FILLER
    pub _filler_317: FixedString<5>,
}
impl std::fmt::Display for ProvNewrecHold1 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self.p_new_npi10, self.p_new_provider_no, self.p_new_date_data, self.p_new_waiver_code, self.p_new_inter_no, self.p_new_provider_type, self.p_new_current_census_div, self.p_new_current_div, self.p_new_msa_data, self.p_new_sol_com_dep_hosp_yr, self.p_new_lugar, self.p_new_temp_relief_ind, self.p_new_fed_pps_blend_ind, self._filler_317)
    }
}
impl From<&str> for ProvNewrecHold1 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ProvNewrecHold1 {
    fn from(_s: String) -> Self { Self::default() }
}
impl ProvNewrecHold1 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PNewNpi10 {
    /// P-NEW-NPI8
    pub p_new_npi8: FixedString<8>,
    /// P-NEW-NPI-FILLER
    pub p_new_npi_filler: FixedString<2>,
}
impl std::fmt::Display for PNewNpi10 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.p_new_npi8, self.p_new_npi_filler)
    }
}
impl From<&str> for PNewNpi10 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PNewNpi10 {
    fn from(_s: String) -> Self { Self::default() }
}
impl PNewNpi10 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PNewProviderNo {
    /// P-NEW-STATE
    pub p_new_state: u32,
    /// FILLER PIC FILLER
    pub _filler_236: FixedString<4>,
}
impl std::fmt::Display for PNewProviderNo {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.p_new_state, self._filler_236)
    }
}
impl From<&str> for PNewProviderNo {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PNewProviderNo {
    fn from(_s: String) -> Self { Self::default() }
}
impl PNewProviderNo {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PNewDateData {
    /// P-NEW-EFF-DATE
    pub p_new_eff_date: PNewEffDate,
    /// P-NEW-FY-BEGIN-DATE
    pub p_new_fy_begin_date: PNewFyBeginDate,
    /// P-NEW-REPORT-DATE
    pub p_new_report_date: PNewReportDate,
    /// P-NEW-TERMINATION-DATE
    pub p_new_termination_date: PNewTerminationDate,
}
impl std::fmt::Display for PNewDateData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.p_new_eff_date, self.p_new_fy_begin_date, self.p_new_report_date, self.p_new_termination_date)
    }
}
impl From<&str> for PNewDateData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PNewDateData {
    fn from(_s: String) -> Self { Self::default() }
}
impl PNewDateData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PNewEffDate {
    /// P-NEW-EFF-DT-CC
    pub p_new_eff_dt_cc: u32,
    /// P-NEW-EFF-DT-YY
    pub p_new_eff_dt_yy: u32,
    /// P-NEW-EFF-DT-MM
    pub p_new_eff_dt_mm: u32,
    /// P-NEW-EFF-DT-DD
    pub p_new_eff_dt_dd: u32,
}
impl std::fmt::Display for PNewEffDate {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.p_new_eff_dt_cc, self.p_new_eff_dt_yy, self.p_new_eff_dt_mm, self.p_new_eff_dt_dd)
    }
}
impl From<&str> for PNewEffDate {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PNewEffDate {
    fn from(_s: String) -> Self { Self::default() }
}
impl PNewEffDate {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PNewFyBeginDate {
    /// P-NEW-FY-BEG-DT-CC
    pub p_new_fy_beg_dt_cc: u32,
    /// P-NEW-FY-BEG-DT-YY
    pub p_new_fy_beg_dt_yy: u32,
    /// P-NEW-FY-BEG-DT-MM
    pub p_new_fy_beg_dt_mm: u32,
    /// P-NEW-FY-BEG-DT-DD
    pub p_new_fy_beg_dt_dd: u32,
}
impl std::fmt::Display for PNewFyBeginDate {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.p_new_fy_beg_dt_cc, self.p_new_fy_beg_dt_yy, self.p_new_fy_beg_dt_mm, self.p_new_fy_beg_dt_dd)
    }
}
impl From<&str> for PNewFyBeginDate {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PNewFyBeginDate {
    fn from(_s: String) -> Self { Self::default() }
}
impl PNewFyBeginDate {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PNewReportDate {
    /// P-NEW-REPORT-DT-CC
    pub p_new_report_dt_cc: u32,
    /// P-NEW-REPORT-DT-YY
    pub p_new_report_dt_yy: u32,
    /// P-NEW-REPORT-DT-MM
    pub p_new_report_dt_mm: u32,
    /// P-NEW-REPORT-DT-DD
    pub p_new_report_dt_dd: u32,
}
impl std::fmt::Display for PNewReportDate {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.p_new_report_dt_cc, self.p_new_report_dt_yy, self.p_new_report_dt_mm, self.p_new_report_dt_dd)
    }
}
impl From<&str> for PNewReportDate {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PNewReportDate {
    fn from(_s: String) -> Self { Self::default() }
}
impl PNewReportDate {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PNewTerminationDate {
    /// P-NEW-TERM-DT-CC
    pub p_new_term_dt_cc: u32,
    /// P-NEW-TERM-DT-YY
    pub p_new_term_dt_yy: u32,
    /// P-NEW-TERM-DT-MM
    pub p_new_term_dt_mm: u32,
    /// P-NEW-TERM-DT-DD
    pub p_new_term_dt_dd: u32,
}
impl std::fmt::Display for PNewTerminationDate {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.p_new_term_dt_cc, self.p_new_term_dt_yy, self.p_new_term_dt_mm, self.p_new_term_dt_dd)
    }
}
impl From<&str> for PNewTerminationDate {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PNewTerminationDate {
    fn from(_s: String) -> Self { Self::default() }
}
impl PNewTerminationDate {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PNewMsaData {
    /// P-NEW-CHG-CODE-INDEX
    pub p_new_chg_code_index: FixedString<1>,
    /// P-NEW-GEO-LOC-MSAX
    pub p_new_geo_loc_msax: FixedString<4>,
    /// P-NEW-GEO-LOC-MSAX-RUR
    pub p_new_geo_loc_msax_rur: PNewGeoLocMsaxRur,
    /// P-NEW-GEO-LOC-MSA9
    pub p_new_geo_loc_msa9: u32,
    /// P-NEW-WAGE-INDEX-LOC-MSA
    pub p_new_wage_index_loc_msa: FixedString<4>,
    /// P-NEW-STAND-AMT-LOC-MSA
    pub p_new_stand_amt_loc_msa: FixedString<4>,
    /// P-NEW-STAND-AMT-LOC-MSA9
    pub p_new_stand_amt_loc_msa9: PNewStandAmtLocMsa9,
}
impl std::fmt::Display for PNewMsaData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}", self.p_new_chg_code_index, self.p_new_geo_loc_msax, self.p_new_geo_loc_msax_rur, self.p_new_geo_loc_msa9, self.p_new_wage_index_loc_msa, self.p_new_stand_amt_loc_msa, self.p_new_stand_amt_loc_msa9)
    }
}
impl From<&str> for PNewMsaData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PNewMsaData {
    fn from(_s: String) -> Self { Self::default() }
}
impl PNewMsaData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PNewGeoLocMsaxRur {
    /// P-NEW-RURAL1
    pub p_new_rural1: FixedString<2>,
    /// P-NEW-GEO-RURAL2
    pub p_new_geo_rural2: FixedString<2>,
}
impl std::fmt::Display for PNewGeoLocMsaxRur {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.p_new_rural1, self.p_new_geo_rural2)
    }
}
impl From<&str> for PNewGeoLocMsaxRur {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PNewGeoLocMsaxRur {
    fn from(_s: String) -> Self { Self::default() }
}
impl PNewGeoLocMsaxRur {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PNewStandAmtLocMsa9 {
    /// P-NEW-RURAL-1ST
    pub p_new_rural_1st: PNewRural1st,
    /// P-NEW-RURAL-2ND
    pub p_new_rural_2nd: FixedString<2>,
}
impl std::fmt::Display for PNewStandAmtLocMsa9 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.p_new_rural_1st, self.p_new_rural_2nd)
    }
}
impl From<&str> for PNewStandAmtLocMsa9 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PNewStandAmtLocMsa9 {
    fn from(_s: String) -> Self { Self::default() }
}
impl PNewStandAmtLocMsa9 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PNewRural1st {
    /// P-NEW-STAND-RURAL
    pub p_new_stand_rural: FixedString<2>,
}
impl std::fmt::Display for PNewRural1st {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.p_new_stand_rural)
    }
}
impl From<&str> for PNewRural1st {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PNewRural1st {
    fn from(_s: String) -> Self { Self::default() }
}
impl PNewRural1st {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ProvNewrecHold2 {
    /// P-NEW-VARIABLES
    pub p_new_variables: PNewVariables,
    /// P-NEW-CBSA-DATA
    pub p_new_cbsa_data: PNewCbsaData,
}
impl std::fmt::Display for ProvNewrecHold2 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.p_new_variables, self.p_new_cbsa_data)
    }
}
impl From<&str> for ProvNewrecHold2 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ProvNewrecHold2 {
    fn from(_s: String) -> Self { Self::default() }
}
impl ProvNewrecHold2 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PNewVariables {
    /// P-NEW-FAC-SPEC-RATE
    pub p_new_fac_spec_rate: Decimal /* 5,2 Unsigned */,
    /// P-NEW-COLA
    pub p_new_cola: Decimal /* 1,3 Unsigned */,
    /// P-NEW-INTERN-RATIO
    pub p_new_intern_ratio: Decimal /* 1,4 Unsigned */,
    /// P-NEW-BED-SIZE
    pub p_new_bed_size: u32,
    /// P-NEW-OPER-CSTCHG-RATIO
    pub p_new_oper_cstchg_ratio: Decimal /* 1,3 Unsigned */,
    /// P-NEW-CMI
    pub p_new_cmi: Decimal /* 1,4 Unsigned */,
    /// P-NEW-SSI-RATIO
    pub p_new_ssi_ratio: Decimal /* 0,4 Unsigned */,
    /// P-NEW-MEDICAID-RATIO
    pub p_new_medicaid_ratio: Decimal /* 0,4 Unsigned */,
    /// P-NEW-PPS-BLEND-YR-IND
    pub p_new_pps_blend_yr_ind: FixedString<1>,
    /// P-NEW-PRUP-UPDATE-FACTOR
    pub p_new_prup_update_factor: Decimal /* 1,5 Unsigned */,
    /// P-NEW-DSH-PERCENT
    pub p_new_dsh_percent: Decimal /* 0,4 Unsigned */,
    /// P-NEW-FYE-DATE
    pub p_new_fye_date: u32,
}
impl std::fmt::Display for PNewVariables {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}", self.p_new_fac_spec_rate, self.p_new_cola, self.p_new_intern_ratio, self.p_new_bed_size, self.p_new_oper_cstchg_ratio, self.p_new_cmi, self.p_new_ssi_ratio, self.p_new_medicaid_ratio, self.p_new_pps_blend_yr_ind, self.p_new_prup_update_factor, self.p_new_dsh_percent, self.p_new_fye_date)
    }
}
impl From<&str> for PNewVariables {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PNewVariables {
    fn from(_s: String) -> Self { Self::default() }
}
impl PNewVariables {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PNewCbsaData {
    /// W-P-NEW-CBSA-SPEC-PAY-IND
    pub w_p_new_cbsa_spec_pay_ind: FixedString<1>,
    /// W-P-NEW-CBSA-HOSP-QUAL-IND
    pub w_p_new_cbsa_hosp_qual_ind: FixedString<1>,
    /// W-P-NEW-CBSA-GEO-LOC
    pub w_p_new_cbsa_geo_loc: FixedString<5>,
    /// W-P-NEW-CBSA-GEO-RURAL
    pub w_p_new_cbsa_geo_rural: WPNewCbsaGeoRural,
    /// W-P-NEW-CBSA-RECLASS-LOC
    pub w_p_new_cbsa_reclass_loc: FixedString<5>,
    /// W-P-NEW-CBSA-STAND-AMT-LOC
    pub w_p_new_cbsa_stand_amt_loc: FixedString<5>,
    /// W-P-NEW-CBSA-SPEC-WAGE-INDEX
    pub w_p_new_cbsa_spec_wage_index: Decimal /* 2,4 Unsigned */,
}
impl std::fmt::Display for PNewCbsaData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}", self.w_p_new_cbsa_spec_pay_ind, self.w_p_new_cbsa_hosp_qual_ind, self.w_p_new_cbsa_geo_loc, self.w_p_new_cbsa_geo_rural, self.w_p_new_cbsa_reclass_loc, self.w_p_new_cbsa_stand_amt_loc, self.w_p_new_cbsa_spec_wage_index)
    }
}
impl From<&str> for PNewCbsaData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PNewCbsaData {
    fn from(_s: String) -> Self { Self::default() }
}
impl PNewCbsaData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WPNewCbsaGeoRural {
    /// W-P-NEW-CBSA-GEO-RURAL1ST
    pub w_p_new_cbsa_geo_rural1st: FixedString<3>,
    /// W-P-NEW-CBSA-GEO-RURAL2ND
    pub w_p_new_cbsa_geo_rural2nd: FixedString<2>,
}
impl std::fmt::Display for WPNewCbsaGeoRural {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.w_p_new_cbsa_geo_rural1st, self.w_p_new_cbsa_geo_rural2nd)
    }
}
impl From<&str> for WPNewCbsaGeoRural {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WPNewCbsaGeoRural {
    fn from(_s: String) -> Self { Self::default() }
}
impl WPNewCbsaGeoRural {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ProvNewrecHold3 {
    /// P-NEW-PASS-AMT-DATA
    pub p_new_pass_amt_data: PNewPassAmtData,
    /// P-NEW-CAPI-DATA
    pub p_new_capi_data: PNewCapiData,
    /// FILLER PIC FILLER
    pub _filler_367: FixedString<18>,
}
impl std::fmt::Display for ProvNewrecHold3 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.p_new_pass_amt_data, self.p_new_capi_data, self._filler_367)
    }
}
impl From<&str> for ProvNewrecHold3 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ProvNewrecHold3 {
    fn from(_s: String) -> Self { Self::default() }
}
impl ProvNewrecHold3 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PNewPassAmtData {
    /// P-NEW-PASS-AMT-CAPITAL
    pub p_new_pass_amt_capital: Decimal /* 4,2 Unsigned */,
    /// P-NEW-PASS-AMT-DIR-MED-ED
    pub p_new_pass_amt_dir_med_ed: Decimal /* 4,2 Unsigned */,
    /// P-NEW-PASS-AMT-ORGAN-ACQ
    pub p_new_pass_amt_organ_acq: Decimal /* 4,2 Unsigned */,
    /// P-NEW-PASS-AMT-PLUS-MISC
    pub p_new_pass_amt_plus_misc: Decimal /* 4,2 Unsigned */,
}
impl std::fmt::Display for PNewPassAmtData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.p_new_pass_amt_capital, self.p_new_pass_amt_dir_med_ed, self.p_new_pass_amt_organ_acq, self.p_new_pass_amt_plus_misc)
    }
}
impl From<&str> for PNewPassAmtData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PNewPassAmtData {
    fn from(_s: String) -> Self { Self::default() }
}
impl PNewPassAmtData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PNewCapiData {
    /// P-NEW-CAPI-PPS-PAY-CODE
    pub p_new_capi_pps_pay_code: FixedString<1>,
    /// P-NEW-CAPI-HOSP-SPEC-RATE
    pub p_new_capi_hosp_spec_rate: Decimal /* 4,2 Unsigned */,
    /// P-NEW-CAPI-OLD-HARM-RATE
    pub p_new_capi_old_harm_rate: Decimal /* 4,2 Unsigned */,
    /// P-NEW-CAPI-NEW-HARM-RATIO
    pub p_new_capi_new_harm_ratio: Decimal /* 1,4 Unsigned */,
    /// P-NEW-CAPI-CSTCHG-RATIO
    pub p_new_capi_cstchg_ratio: Decimal /* 1,3 Unsigned */,
    /// P-NEW-CAPI-NEW-HOSP
    pub p_new_capi_new_hosp: FixedString<1>,
    /// P-NEW-CAPI-IME
    pub p_new_capi_ime: Decimal /* 1,4 Unsigned */,
    /// P-NEW-CAPI-EXCEPTIONS
    pub p_new_capi_exceptions: Decimal /* 4,2 Unsigned */,
    /// P-VAL-BASED-PURCH-SCORE
    pub p_val_based_purch_score: Decimal /* 1,3 Unsigned */,
}
impl std::fmt::Display for PNewCapiData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}", self.p_new_capi_pps_pay_code, self.p_new_capi_hosp_spec_rate, self.p_new_capi_old_harm_rate, self.p_new_capi_new_harm_ratio, self.p_new_capi_cstchg_ratio, self.p_new_capi_new_hosp, self.p_new_capi_ime, self.p_new_capi_exceptions, self.p_val_based_purch_score)
    }
}
impl From<&str> for PNewCapiData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PNewCapiData {
    fn from(_s: String) -> Self { Self::default() }
}
impl PNewCapiData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WFyBeginDate {
    /// W-FY-BEGIN-CC
    pub w_fy_begin_cc: u32,
    /// W-FY-BEGIN-YY
    pub w_fy_begin_yy: u32,
    /// W-FY-BEGIN-MM
    pub w_fy_begin_mm: u32,
    /// W-FY-BEGIN-DD
    pub w_fy_begin_dd: u32,
}
impl std::fmt::Display for WFyBeginDate {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.w_fy_begin_cc, self.w_fy_begin_yy, self.w_fy_begin_mm, self.w_fy_begin_dd)
    }
}
impl From<&str> for WFyBeginDate {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WFyBeginDate {
    fn from(_s: String) -> Self { Self::default() }
}
impl WFyBeginDate {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WFyEndDate {
    /// W-FY-END-CC
    pub w_fy_end_cc: u32,
    /// W-FY-END-YY
    pub w_fy_end_yy: u32,
    /// W-FY-END-MM
    pub w_fy_end_mm: u32,
    /// W-FY-END-DD
    pub w_fy_end_dd: u32,
}
impl std::fmt::Display for WFyEndDate {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.w_fy_end_cc, self.w_fy_end_yy, self.w_fy_end_mm, self.w_fy_end_dd)
    }
}
impl From<&str> for WFyEndDate {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WFyEndDate {
    fn from(_s: String) -> Self { Self::default() }
}
impl WFyEndDate {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Bill315Data {
    /// BILL-NPI
    pub bill_npi: FixedString<10>,
    /// BILL-PROV-NO
    pub bill_prov_no: FixedString<6>,
    /// BILL-FROM-DATE
    pub bill_from_date: BillFromDate,
    /// BILL-ADMISSION-DATE
    pub bill_admission_date: BillAdmissionDate,
    /// FILLER PIC FILLER
    pub _filler_443: FixedString<10>,
    /// BILL-PROV-MSA-LUGAR
    pub bill_prov_msa_lugar: BillProvMsaLugar,
    /// BILL-PROV-CBSA
    pub bill_prov_cbsa: FixedString<5>,
    /// BILL-BENE-MSA-LUGAR
    pub bill_bene_msa_lugar: BillBeneMsaLugar,
    /// BILL-BENE-CBSA
    pub bill_bene_cbsa: FixedString<5>,
    /// BILL-PROV-WAGE-INDEX
    pub bill_prov_wage_index: Decimal /* 2,4 Unsigned */,
    /// BILL-BENE-WAGE-INDEX
    pub bill_bene_wage_index: Decimal /* 2,4 Unsigned */,
    /// BILL-SIA-ADD-ON-UNITS
    pub bill_sia_add_on_units: BillSiaAddOnUnits,
    /// FILLER PIC FILLER
    pub _filler_471: FixedString<10>,
    /// BILL-QIP-IND
    pub bill_qip_ind: FixedString<1>,
    /// BILL-GROUP1
    pub bill_group1: BillGroup1,
    /// BILL-GROUP2
    pub bill_group2: BillGroup2,
    /// BILL-GROUP3
    pub bill_group3: BillGroup3,
    /// BILL-GROUP4
    pub bill_group4: BillGroup4,
    /// BILL-SIA-ADD-ON-PYMTS
    pub bill_sia_add_on_pymts: BillSiaAddOnPymts,
    /// BILL-RETURNED-DATA
    pub bill_returned_data: BillReturnedData,
    /// BILL-RHC-DAYS-PAID
    pub bill_rhc_days_paid: BillRhcDaysPaid,
    /// FILLER PIC FILLER
    pub _filler_536: FixedString<8>,
}
impl std::fmt::Display for Bill315Data {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self.bill_npi, self.bill_prov_no, self.bill_from_date, self.bill_admission_date, self._filler_443, self.bill_prov_msa_lugar, self.bill_prov_cbsa, self.bill_bene_msa_lugar, self.bill_bene_cbsa, self.bill_prov_wage_index, self.bill_bene_wage_index, self.bill_sia_add_on_units, self._filler_471, self.bill_qip_ind, self.bill_group1, self.bill_group2, self.bill_group3, self.bill_group4, self.bill_sia_add_on_pymts, self.bill_returned_data, self.bill_rhc_days_paid, self._filler_536)
    }
}
impl From<&str> for Bill315Data {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Bill315Data {
    fn from(_s: String) -> Self { Self::default() }
}
impl Bill315Data {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BillFromDate {
    /// BILL-FROM-CC
    pub bill_from_cc: u32,
    /// BILL-FROM-YY
    pub bill_from_yy: u32,
    /// BILL-FROM-MM
    pub bill_from_mm: u32,
    /// BILL-FROM-DD
    pub bill_from_dd: u32,
}
impl std::fmt::Display for BillFromDate {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.bill_from_cc, self.bill_from_yy, self.bill_from_mm, self.bill_from_dd)
    }
}
impl From<&str> for BillFromDate {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BillFromDate {
    fn from(_s: String) -> Self { Self::default() }
}
impl BillFromDate {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BillAdmissionDate {
    /// BILL-ADM-CC
    pub bill_adm_cc: u32,
    /// BILL-ADM-YY
    pub bill_adm_yy: u32,
    /// BILL-ADM-MM
    pub bill_adm_mm: u32,
    /// BILL-ADM-DD
    pub bill_adm_dd: u32,
}
impl std::fmt::Display for BillAdmissionDate {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.bill_adm_cc, self.bill_adm_yy, self.bill_adm_mm, self.bill_adm_dd)
    }
}
impl From<&str> for BillAdmissionDate {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BillAdmissionDate {
    fn from(_s: String) -> Self { Self::default() }
}
impl BillAdmissionDate {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BillProvMsaLugar {
    /// BILL-PROV-MSA
    pub bill_prov_msa: FixedString<4>,
    /// BILL-PROV-LUGAR
    pub bill_prov_lugar: FixedString<1>,
}
impl std::fmt::Display for BillProvMsaLugar {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.bill_prov_msa, self.bill_prov_lugar)
    }
}
impl From<&str> for BillProvMsaLugar {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BillProvMsaLugar {
    fn from(_s: String) -> Self { Self::default() }
}
impl BillProvMsaLugar {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BillBeneMsaLugar {
    /// BILL-BENE-MSA
    pub bill_bene_msa: FixedString<4>,
    /// BILL-BENE-LUGAR
    pub bill_bene_lugar: FixedString<1>,
}
impl std::fmt::Display for BillBeneMsaLugar {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.bill_bene_msa, self.bill_bene_lugar)
    }
}
impl From<&str> for BillBeneMsaLugar {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BillBeneMsaLugar {
    fn from(_s: String) -> Self { Self::default() }
}
impl BillBeneMsaLugar {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BillSiaAddOnUnits {
    /// BILL-NA-ADD-ON-DAY1-UNITS
    pub bill_na_add_on_day1_units: u32,
    /// BILL-NA-ADD-ON-DAY2-UNITS
    pub bill_na_add_on_day2_units: u32,
    /// BILL-EOL-ADD-ON-DAY1-UNITS
    pub bill_eol_add_on_day1_units: u32,
    /// BILL-EOL-ADD-ON-DAY2-UNITS
    pub bill_eol_add_on_day2_units: u32,
    /// BILL-EOL-ADD-ON-DAY3-UNITS
    pub bill_eol_add_on_day3_units: u32,
    /// BILL-EOL-ADD-ON-DAY4-UNITS
    pub bill_eol_add_on_day4_units: u32,
    /// BILL-EOL-ADD-ON-DAY5-UNITS
    pub bill_eol_add_on_day5_units: u32,
    /// BILL-EOL-ADD-ON-DAY6-UNITS
    pub bill_eol_add_on_day6_units: u32,
    /// BILL-EOL-ADD-ON-DAY7-UNITS
    pub bill_eol_add_on_day7_units: u32,
}
impl std::fmt::Display for BillSiaAddOnUnits {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}", self.bill_na_add_on_day1_units, self.bill_na_add_on_day2_units, self.bill_eol_add_on_day1_units, self.bill_eol_add_on_day2_units, self.bill_eol_add_on_day3_units, self.bill_eol_add_on_day4_units, self.bill_eol_add_on_day5_units, self.bill_eol_add_on_day6_units, self.bill_eol_add_on_day7_units)
    }
}
impl From<&str> for BillSiaAddOnUnits {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BillSiaAddOnUnits {
    fn from(_s: String) -> Self { Self::default() }
}
impl BillSiaAddOnUnits {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BillGroup1 {
    /// BILL-REV1
    pub bill_rev1: FixedString<4>,
    /// BILL-HCPC1
    pub bill_hcpc1: FixedString<5>,
    /// BILL-LINE-ITEM-DOS1
    pub bill_line_item_dos1: BillLineItemDos1,
    /// BILL-UNITS1
    pub bill_units1: u32,
    /// BILL-PAY-AMT1
    pub bill_pay_amt1: Decimal /* 6,2 Unsigned */,
}
impl std::fmt::Display for BillGroup1 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}", self.bill_rev1, self.bill_hcpc1, self.bill_line_item_dos1, self.bill_units1, self.bill_pay_amt1)
    }
}
impl From<&str> for BillGroup1 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BillGroup1 {
    fn from(_s: String) -> Self { Self::default() }
}
impl BillGroup1 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BillLineItemDos1 {
    /// BILL-LIDOS1-CC
    pub bill_lidos1_cc: u32,
    /// BILL-LIDOS1-YY
    pub bill_lidos1_yy: u32,
    /// BILL-LIDOS1-MM
    pub bill_lidos1_mm: u32,
    /// BILL-LIDOS1-DD
    pub bill_lidos1_dd: u32,
}
impl std::fmt::Display for BillLineItemDos1 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.bill_lidos1_cc, self.bill_lidos1_yy, self.bill_lidos1_mm, self.bill_lidos1_dd)
    }
}
impl From<&str> for BillLineItemDos1 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BillLineItemDos1 {
    fn from(_s: String) -> Self { Self::default() }
}
impl BillLineItemDos1 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BillGroup2 {
    /// BILL-REV2
    pub bill_rev2: FixedString<4>,
    /// BILL-HCPC2
    pub bill_hcpc2: FixedString<5>,
    /// BILL-LINE-ITEM-DOS2
    pub bill_line_item_dos2: BillLineItemDos2,
    /// BILL-UNITS2
    pub bill_units2: u32,
    /// BILL-PAY-AMT2
    pub bill_pay_amt2: Decimal /* 6,2 Unsigned */,
}
impl std::fmt::Display for BillGroup2 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}", self.bill_rev2, self.bill_hcpc2, self.bill_line_item_dos2, self.bill_units2, self.bill_pay_amt2)
    }
}
impl From<&str> for BillGroup2 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BillGroup2 {
    fn from(_s: String) -> Self { Self::default() }
}
impl BillGroup2 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BillLineItemDos2 {
    /// BILL-LIDOS2-CC
    pub bill_lidos2_cc: u32,
    /// BILL-LIDOS2-YY
    pub bill_lidos2_yy: u32,
    /// BILL-LIDOS2-MM
    pub bill_lidos2_mm: u32,
    /// BILL-LIDOS2-DD
    pub bill_lidos2_dd: u32,
}
impl std::fmt::Display for BillLineItemDos2 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.bill_lidos2_cc, self.bill_lidos2_yy, self.bill_lidos2_mm, self.bill_lidos2_dd)
    }
}
impl From<&str> for BillLineItemDos2 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BillLineItemDos2 {
    fn from(_s: String) -> Self { Self::default() }
}
impl BillLineItemDos2 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BillGroup3 {
    /// BILL-REV3
    pub bill_rev3: FixedString<4>,
    /// BILL-HCPC3
    pub bill_hcpc3: FixedString<5>,
    /// BILL-LINE-ITEM-DOS3
    pub bill_line_item_dos3: BillLineItemDos3,
    /// BILL-UNITS3
    pub bill_units3: u32,
    /// BILL-PAY-AMT3
    pub bill_pay_amt3: Decimal /* 6,2 Unsigned */,
}
impl std::fmt::Display for BillGroup3 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}", self.bill_rev3, self.bill_hcpc3, self.bill_line_item_dos3, self.bill_units3, self.bill_pay_amt3)
    }
}
impl From<&str> for BillGroup3 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BillGroup3 {
    fn from(_s: String) -> Self { Self::default() }
}
impl BillGroup3 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BillLineItemDos3 {
    /// BILL-LIDOS3-CC
    pub bill_lidos3_cc: u32,
    /// BILL-LIDOS3-YY
    pub bill_lidos3_yy: u32,
    /// BILL-LIDOS3-MM
    pub bill_lidos3_mm: u32,
    /// BILL-LIDOS3-DD
    pub bill_lidos3_dd: u32,
}
impl std::fmt::Display for BillLineItemDos3 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.bill_lidos3_cc, self.bill_lidos3_yy, self.bill_lidos3_mm, self.bill_lidos3_dd)
    }
}
impl From<&str> for BillLineItemDos3 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BillLineItemDos3 {
    fn from(_s: String) -> Self { Self::default() }
}
impl BillLineItemDos3 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BillGroup4 {
    /// BILL-REV4
    pub bill_rev4: FixedString<4>,
    /// BILL-HCPC4
    pub bill_hcpc4: FixedString<5>,
    /// BILL-LINE-ITEM-DOS4
    pub bill_line_item_dos4: BillLineItemDos4,
    /// BILL-UNITS4
    pub bill_units4: u32,
    /// BILL-PAY-AMT4
    pub bill_pay_amt4: Decimal /* 6,2 Unsigned */,
}
impl std::fmt::Display for BillGroup4 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}", self.bill_rev4, self.bill_hcpc4, self.bill_line_item_dos4, self.bill_units4, self.bill_pay_amt4)
    }
}
impl From<&str> for BillGroup4 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BillGroup4 {
    fn from(_s: String) -> Self { Self::default() }
}
impl BillGroup4 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BillLineItemDos4 {
    /// BILL-LIDOS4-CC
    pub bill_lidos4_cc: u32,
    /// BILL-LIDOS4-YY
    pub bill_lidos4_yy: u32,
    /// BILL-LIDOS4-MM
    pub bill_lidos4_mm: u32,
    /// BILL-LIDOS4-DD
    pub bill_lidos4_dd: u32,
}
impl std::fmt::Display for BillLineItemDos4 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.bill_lidos4_cc, self.bill_lidos4_yy, self.bill_lidos4_mm, self.bill_lidos4_dd)
    }
}
impl From<&str> for BillLineItemDos4 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BillLineItemDos4 {
    fn from(_s: String) -> Self { Self::default() }
}
impl BillLineItemDos4 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BillSiaAddOnPymts {
    /// BILL-NA-ADD-ON-DAY1-PAY
    pub bill_na_add_on_day1_pay: Decimal /* 6,2 Unsigned */,
    /// BILL-NA-ADD-ON-DAY2-PAY
    pub bill_na_add_on_day2_pay: Decimal /* 6,2 Unsigned */,
    /// BILL-EOL-ADD-ON-DAY1-PAY
    pub bill_eol_add_on_day1_pay: Decimal /* 6,2 Unsigned */,
    /// BILL-EOL-ADD-ON-DAY2-PAY
    pub bill_eol_add_on_day2_pay: Decimal /* 6,2 Unsigned */,
    /// BILL-EOL-ADD-ON-DAY3-PAY
    pub bill_eol_add_on_day3_pay: Decimal /* 6,2 Unsigned */,
    /// BILL-EOL-ADD-ON-DAY4-PAY
    pub bill_eol_add_on_day4_pay: Decimal /* 6,2 Unsigned */,
    /// BILL-EOL-ADD-ON-DAY5-PAY
    pub bill_eol_add_on_day5_pay: Decimal /* 6,2 Unsigned */,
    /// BILL-EOL-ADD-ON-DAY6-PAY
    pub bill_eol_add_on_day6_pay: Decimal /* 6,2 Unsigned */,
    /// BILL-EOL-ADD-ON-DAY7-PAY
    pub bill_eol_add_on_day7_pay: Decimal /* 6,2 Unsigned */,
}
impl std::fmt::Display for BillSiaAddOnPymts {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}", self.bill_na_add_on_day1_pay, self.bill_na_add_on_day2_pay, self.bill_eol_add_on_day1_pay, self.bill_eol_add_on_day2_pay, self.bill_eol_add_on_day3_pay, self.bill_eol_add_on_day4_pay, self.bill_eol_add_on_day5_pay, self.bill_eol_add_on_day6_pay, self.bill_eol_add_on_day7_pay)
    }
}
impl From<&str> for BillSiaAddOnPymts {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BillSiaAddOnPymts {
    fn from(_s: String) -> Self { Self::default() }
}
impl BillSiaAddOnPymts {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BillReturnedData {
    /// BILL-PAY-AMT-TOTAL
    pub bill_pay_amt_total: Decimal /* 6,2 Unsigned */,
    /// BILL-RTC
    pub bill_rtc: FixedString<2>,
}
impl std::fmt::Display for BillReturnedData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.bill_pay_amt_total, self.bill_rtc)
    }
}
impl From<&str> for BillReturnedData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BillReturnedData {
    fn from(_s: String) -> Self { Self::default() }
}
impl BillReturnedData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct BillRhcDaysPaid {
    /// BILL-HIGH-RHC-DAYS
    pub bill_high_rhc_days: u32,
    /// BILL-LOW-RHC-DAYS
    pub bill_low_rhc_days: u32,
}
impl std::fmt::Display for BillRhcDaysPaid {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.bill_high_rhc_days, self.bill_low_rhc_days)
    }
}
impl From<&str> for BillRhcDaysPaid {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for BillRhcDaysPaid {
    fn from(_s: String) -> Self { Self::default() }
}
impl BillRhcDaysPaid {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, PartialEq)]
pub struct ProvTable {
    /// PROV-ENTRIES
    pub prov_entries: [ProvEntries; 2400],
}
impl Default for ProvTable {
    fn default() -> Self {
        Self {
            prov_entries: std::array::from_fn(|_| Default::default()),
        }
    }
}
impl std::fmt::Display for ProvTable {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "")
    }
}
impl From<&str> for ProvTable {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ProvTable {
    fn from(_s: String) -> Self { Self::default() }
}
impl ProvTable {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ProvEntries {
    /// PROV-DATA1
    pub prov_data1: ProvData1,
}
impl std::fmt::Display for ProvEntries {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.prov_data1)
    }
}
impl From<&str> for ProvEntries {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ProvEntries {
    fn from(_s: String) -> Self { Self::default() }
}
impl ProvEntries {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ProvData1 {
    /// PROV-NPI10
    pub prov_npi10: ProvNpi10,
    /// PROV-NO
    pub prov_no: FixedString<6>,
    /// PROV-EFF-DATE
    pub prov_eff_date: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_560: FixedString<56>,
}
impl std::fmt::Display for ProvData1 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.prov_npi10, self.prov_no, self.prov_eff_date, self._filler_560)
    }
}
impl From<&str> for ProvData1 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ProvData1 {
    fn from(_s: String) -> Self { Self::default() }
}
impl ProvData1 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ProvNpi10 {
    /// PROV-NPI8
    pub prov_npi8: FixedString<8>,
    /// PROV-NPI-FIL
    pub prov_npi_fil: FixedString<2>,
}
impl std::fmt::Display for ProvNpi10 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.prov_npi8, self.prov_npi_fil)
    }
}
impl From<&str> for ProvNpi10 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ProvNpi10 {
    fn from(_s: String) -> Self { Self::default() }
}
impl ProvNpi10 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, PartialEq)]
pub struct ProvData2 {
    /// PROV-ENTRIES2
    pub prov_entries2: [ProvEntries2; 2400],
}
impl Default for ProvData2 {
    fn default() -> Self {
        Self {
            prov_entries2: std::array::from_fn(|_| Default::default()),
        }
    }
}
impl std::fmt::Display for ProvData2 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "")
    }
}
impl From<&str> for ProvData2 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ProvData2 {
    fn from(_s: String) -> Self { Self::default() }
}
impl ProvData2 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ProvEntries2 {
    /// PROV-DATA2
    pub prov_data2: FixedString<80>,
}
impl std::fmt::Display for ProvEntries2 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.prov_data2)
    }
}
impl From<&str> for ProvEntries2 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ProvEntries2 {
    fn from(_s: String) -> Self { Self::default() }
}
impl ProvEntries2 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, PartialEq)]
pub struct ProvData3 {
    /// PROV-ENTRIES3
    pub prov_entries3: [ProvEntries3; 2400],
}
impl Default for ProvData3 {
    fn default() -> Self {
        Self {
            prov_entries3: std::array::from_fn(|_| Default::default()),
        }
    }
}
impl std::fmt::Display for ProvData3 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "")
    }
}
impl From<&str> for ProvData3 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ProvData3 {
    fn from(_s: String) -> Self { Self::default() }
}
impl ProvData3 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ProvEntries3 {
    /// PROV-DATA3
    pub prov_data3: FixedString<80>,
}
impl std::fmt::Display for ProvEntries3 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.prov_data3)
    }
}
impl From<&str> for ProvEntries3 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ProvEntries3 {
    fn from(_s: String) -> Self { Self::default() }
}
impl ProvEntries3 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, PartialEq)]
pub struct MsaWiTable {
    /// M-MSA-DATA
    pub m_msa_data: [MMsaData; 4000],
}
impl Default for MsaWiTable {
    fn default() -> Self {
        Self {
            m_msa_data: std::array::from_fn(|_| Default::default()),
        }
    }
}
impl std::fmt::Display for MsaWiTable {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "")
    }
}
impl From<&str> for MsaWiTable {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for MsaWiTable {
    fn from(_s: String) -> Self { Self::default() }
}
impl MsaWiTable {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct MMsaData {
    /// MSA-MSA-LUGAR
    pub msa_msa_lugar: MsaMsaLugar,
    /// MSA-EFFDTE
    pub msa_effdte: FixedString<8>,
    /// MSA-WAGE-IND
    pub msa_wage_ind: Decimal /* 2,4 Signed */,
}
impl std::fmt::Display for MMsaData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.msa_msa_lugar, self.msa_effdte, self.msa_wage_ind)
    }
}
impl From<&str> for MMsaData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for MMsaData {
    fn from(_s: String) -> Self { Self::default() }
}
impl MMsaData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct MsaMsaLugar {
    /// MSA-MSA
    pub msa_msa: u32,
    /// MSA-LUGAR
    pub msa_lugar: FixedString<1>,
}
impl std::fmt::Display for MsaMsaLugar {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.msa_msa, self.msa_lugar)
    }
}
impl From<&str> for MsaMsaLugar {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for MsaMsaLugar {
    fn from(_s: String) -> Self { Self::default() }
}
impl MsaMsaLugar {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, PartialEq)]
pub struct CbsaWiTable {
    /// M-CBSA-DATA
    pub m_cbsa_data: [MCbsaData; 9000],
}
impl Default for CbsaWiTable {
    fn default() -> Self {
        Self {
            m_cbsa_data: std::array::from_fn(|_| Default::default()),
        }
    }
}
impl std::fmt::Display for CbsaWiTable {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "")
    }
}
impl From<&str> for CbsaWiTable {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CbsaWiTable {
    fn from(_s: String) -> Self { Self::default() }
}
impl CbsaWiTable {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct MCbsaData {
    /// M-CBSA
    pub m_cbsa: u32,
    /// M-CBSA-EFFDTE
    pub m_cbsa_effdte: FixedString<8>,
    /// M-CBSA-WAGE-IND
    pub m_cbsa_wage_ind: Decimal /* 2,4 Signed */,
}
impl std::fmt::Display for MCbsaData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.m_cbsa, self.m_cbsa_effdte, self.m_cbsa_wage_ind)
    }
}
impl From<&str> for MCbsaData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for MCbsaData {
    fn from(_s: String) -> Self { Self::default() }
}
impl MCbsaData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// W-STORAGE-REF
    pub w_storage_ref: FixedString<46>,
    /// HOS-VERSION
    pub hos_version: FixedString<9>,
    /// HOSOP210
    pub hosop210: FixedString<8>,
    /// HOSPR210
    pub hospr210: FixedString<8>,
    /// EOF-MSA-SW
    pub eof_msa_sw: u32,
    /// EOF-CBSA-SW
    pub eof_cbsa_sw: u32,
    /// EOF-BILL-SW
    pub eof_bill_sw: u32,
    /// EOF-PROV-SW
    pub eof_prov_sw: u32,
    /// BILL-CTR
    pub bill_ctr: u32,
    /// RATE-CTR
    pub rate_ctr: u32,
    /// PROV-CTR
    pub prov_ctr: u32,
    /// SEARCH-MSA-LUGAR
    pub search_msa_lugar: SearchMsaLugar,
    /// SEARCH-MSA
    pub search_msa: SearchMsa,
    /// SEARCH-MSA-POS12
    pub search_msa_pos12: u32,
    /// SEARCH-MSA-POS34
    pub search_msa_pos34: u32,
    /// SEARCH-LUGAR
    pub search_lugar: FixedString<1>,
    /// SEARCH-CBSA
    pub search_cbsa: SearchCbsa,
    /// SEARCH-CBSA-POS123
    pub search_cbsa_pos123: u32,
    /// SEARCH-CBSA-POS45
    pub search_cbsa_pos45: u32,
    /// UT1-STAT
    pub ut1_stat: Ut1Stat,
    /// UT1-STAT1
    pub ut1_stat1: FixedString<1>,
    /// UT1-STAT2
    pub ut1_stat2: FixedString<1>,
    /// UT2-STAT
    pub ut2_stat: Ut2Stat,
    /// UT2-STAT1
    pub ut2_stat1: FixedString<1>,
    /// UT2-STAT2
    pub ut2_stat2: FixedString<1>,
    /// UT3-STAT
    pub ut3_stat: Ut3Stat,
    /// UT3-STAT1
    pub ut3_stat1: FixedString<1>,
    /// UT3-STAT2
    pub ut3_stat2: FixedString<1>,
    /// UT4-STAT
    pub ut4_stat: Ut4Stat,
    /// UT4-STAT1
    pub ut4_stat1: FixedString<1>,
    /// UT4-STAT2
    pub ut4_stat2: FixedString<1>,
    /// UT5-STAT
    pub ut5_stat: Ut5Stat,
    /// UT5-STAT1
    pub ut5_stat1: FixedString<1>,
    /// UT5-STAT2
    pub ut5_stat2: FixedString<1>,
    /// PROV-NEW-HOLD
    pub prov_new_hold: ProvNewHold,
    /// PROV-NEWREC-HOLD1
    pub prov_newrec_hold1: ProvNewrecHold1,
    /// P-NEW-NPI10
    pub p_new_npi10: PNewNpi10,
    /// P-NEW-NPI8
    pub p_new_npi8: FixedString<8>,
    /// P-NEW-NPI-FILLER
    pub p_new_npi_filler: FixedString<2>,
    /// P-NEW-PROVIDER-NO
    pub p_new_provider_no: PNewProviderNo,
    /// P-NEW-STATE
    pub p_new_state: u32,
    /// P-NEW-DATE-DATA
    pub p_new_date_data: PNewDateData,
    /// P-NEW-EFF-DATE
    pub p_new_eff_date: PNewEffDate,
    /// P-NEW-EFF-DT-CC
    pub p_new_eff_dt_cc: u32,
    /// P-NEW-EFF-DT-YY
    pub p_new_eff_dt_yy: u32,
    /// P-NEW-EFF-DT-MM
    pub p_new_eff_dt_mm: u32,
    /// P-NEW-EFF-DT-DD
    pub p_new_eff_dt_dd: u32,
    /// P-NEW-FY-BEGIN-DATE
    pub p_new_fy_begin_date: PNewFyBeginDate,
    /// P-NEW-FY-BEG-DT-CC
    pub p_new_fy_beg_dt_cc: u32,
    /// P-NEW-FY-BEG-DT-YY
    pub p_new_fy_beg_dt_yy: u32,
    /// P-NEW-FY-BEG-DT-MM
    pub p_new_fy_beg_dt_mm: u32,
    /// P-NEW-FY-BEG-DT-DD
    pub p_new_fy_beg_dt_dd: u32,
    /// P-NEW-REPORT-DATE
    pub p_new_report_date: PNewReportDate,
    /// P-NEW-REPORT-DT-CC
    pub p_new_report_dt_cc: u32,
    /// P-NEW-REPORT-DT-YY
    pub p_new_report_dt_yy: u32,
    /// P-NEW-REPORT-DT-MM
    pub p_new_report_dt_mm: u32,
    /// P-NEW-REPORT-DT-DD
    pub p_new_report_dt_dd: u32,
    /// P-NEW-TERMINATION-DATE
    pub p_new_termination_date: PNewTerminationDate,
    /// P-NEW-TERM-DT-CC
    pub p_new_term_dt_cc: u32,
    /// P-NEW-TERM-DT-YY
    pub p_new_term_dt_yy: u32,
    /// P-NEW-TERM-DT-MM
    pub p_new_term_dt_mm: u32,
    /// P-NEW-TERM-DT-DD
    pub p_new_term_dt_dd: u32,
    /// P-NEW-WAIVER-CODE
    pub p_new_waiver_code: FixedString<1>,
    /// P-NEW-INTER-NO
    pub p_new_inter_no: u32,
    /// P-NEW-PROVIDER-TYPE
    pub p_new_provider_type: FixedString<2>,
    /// P-NEW-CURRENT-CENSUS-DIV
    pub p_new_current_census_div: u32,
    /// P-NEW-MSA-DATA
    pub p_new_msa_data: PNewMsaData,
    /// P-NEW-CHG-CODE-INDEX
    pub p_new_chg_code_index: FixedString<1>,
    /// P-NEW-GEO-LOC-MSAX
    pub p_new_geo_loc_msax: FixedString<4>,
    /// P-NEW-WAGE-INDEX-LOC-MSA
    pub p_new_wage_index_loc_msa: FixedString<4>,
    /// P-NEW-STAND-AMT-LOC-MSA
    pub p_new_stand_amt_loc_msa: FixedString<4>,
    /// P-NEW-SOL-COM-DEP-HOSP-YR
    pub p_new_sol_com_dep_hosp_yr: FixedString<2>,
    /// P-NEW-LUGAR
    pub p_new_lugar: FixedString<1>,
    /// P-NEW-TEMP-RELIEF-IND
    pub p_new_temp_relief_ind: FixedString<1>,
    /// P-NEW-FED-PPS-BLEND-IND
    pub p_new_fed_pps_blend_ind: FixedString<1>,
    /// PROV-NEWREC-HOLD2
    pub prov_newrec_hold2: ProvNewrecHold2,
    /// P-NEW-VARIABLES
    pub p_new_variables: PNewVariables,
    /// P-NEW-FAC-SPEC-RATE
    pub p_new_fac_spec_rate: Decimal /* 5,2 Unsigned */,
    /// P-NEW-COLA
    pub p_new_cola: Decimal /* 1,3 Unsigned */,
    /// P-NEW-INTERN-RATIO
    pub p_new_intern_ratio: Decimal /* 1,4 Unsigned */,
    /// P-NEW-BED-SIZE
    pub p_new_bed_size: u32,
    /// P-NEW-OPER-CSTCHG-RATIO
    pub p_new_oper_cstchg_ratio: Decimal /* 1,3 Unsigned */,
    /// P-NEW-CMI
    pub p_new_cmi: Decimal /* 1,4 Unsigned */,
    /// P-NEW-SSI-RATIO
    pub p_new_ssi_ratio: Decimal /* 0,4 Unsigned */,
    /// P-NEW-MEDICAID-RATIO
    pub p_new_medicaid_ratio: Decimal /* 0,4 Unsigned */,
    /// P-NEW-PPS-BLEND-YR-IND
    pub p_new_pps_blend_yr_ind: FixedString<1>,
    /// P-NEW-PRUP-UPDATE-FACTOR
    pub p_new_prup_update_factor: Decimal /* 1,5 Unsigned */,
    /// P-NEW-DSH-PERCENT
    pub p_new_dsh_percent: Decimal /* 0,4 Unsigned */,
    /// P-NEW-FYE-DATE
    pub p_new_fye_date: u32,
    /// P-NEW-CBSA-DATA
    pub p_new_cbsa_data: PNewCbsaData,
    /// W-P-NEW-CBSA-SPEC-PAY-IND
    pub w_p_new_cbsa_spec_pay_ind: FixedString<1>,
    /// W-P-NEW-CBSA-HOSP-QUAL-IND
    pub w_p_new_cbsa_hosp_qual_ind: FixedString<1>,
    /// W-P-NEW-CBSA-GEO-LOC
    pub w_p_new_cbsa_geo_loc: FixedString<5>,
    /// W-P-NEW-CBSA-RECLASS-LOC
    pub w_p_new_cbsa_reclass_loc: FixedString<5>,
    /// W-P-NEW-CBSA-STAND-AMT-LOC
    pub w_p_new_cbsa_stand_amt_loc: FixedString<5>,
    /// W-P-NEW-CBSA-SPEC-WAGE-INDEX
    pub w_p_new_cbsa_spec_wage_index: Decimal /* 2,4 Unsigned */,
    /// PROV-NEWREC-HOLD3
    pub prov_newrec_hold3: ProvNewrecHold3,
    /// P-NEW-PASS-AMT-DATA
    pub p_new_pass_amt_data: PNewPassAmtData,
    /// P-NEW-PASS-AMT-CAPITAL
    pub p_new_pass_amt_capital: Decimal /* 4,2 Unsigned */,
    /// P-NEW-PASS-AMT-DIR-MED-ED
    pub p_new_pass_amt_dir_med_ed: Decimal /* 4,2 Unsigned */,
    /// P-NEW-PASS-AMT-ORGAN-ACQ
    pub p_new_pass_amt_organ_acq: Decimal /* 4,2 Unsigned */,
    /// P-NEW-PASS-AMT-PLUS-MISC
    pub p_new_pass_amt_plus_misc: Decimal /* 4,2 Unsigned */,
    /// P-NEW-CAPI-DATA
    pub p_new_capi_data: PNewCapiData,
    /// P-NEW-CAPI-PPS-PAY-CODE
    pub p_new_capi_pps_pay_code: FixedString<1>,
    /// P-NEW-CAPI-HOSP-SPEC-RATE
    pub p_new_capi_hosp_spec_rate: Decimal /* 4,2 Unsigned */,
    /// P-NEW-CAPI-OLD-HARM-RATE
    pub p_new_capi_old_harm_rate: Decimal /* 4,2 Unsigned */,
    /// P-NEW-CAPI-NEW-HARM-RATIO
    pub p_new_capi_new_harm_ratio: Decimal /* 1,4 Unsigned */,
    /// P-NEW-CAPI-CSTCHG-RATIO
    pub p_new_capi_cstchg_ratio: Decimal /* 1,3 Unsigned */,
    /// P-NEW-CAPI-NEW-HOSP
    pub p_new_capi_new_hosp: FixedString<1>,
    /// P-NEW-CAPI-IME
    pub p_new_capi_ime: Decimal /* 1,4 Unsigned */,
    /// P-NEW-CAPI-EXCEPTIONS
    pub p_new_capi_exceptions: Decimal /* 4,2 Unsigned */,
    /// P-VAL-BASED-PURCH-SCORE
    pub p_val_based_purch_score: Decimal /* 1,3 Unsigned */,
    /// W-FY-BEGIN-DATE
    pub w_fy_begin_date: WFyBeginDate,
    /// W-FY-BEGIN-CC
    pub w_fy_begin_cc: u32,
    /// W-FY-BEGIN-YY
    pub w_fy_begin_yy: u32,
    /// W-FY-BEGIN-MM
    pub w_fy_begin_mm: u32,
    /// W-FY-BEGIN-DD
    pub w_fy_begin_dd: u32,
    /// W-FY-END-DATE
    pub w_fy_end_date: WFyEndDate,
    /// W-FY-END-CC
    pub w_fy_end_cc: u32,
    /// W-FY-END-YY
    pub w_fy_end_yy: u32,
    /// W-FY-END-MM
    pub w_fy_end_mm: u32,
    /// W-FY-END-DD
    pub w_fy_end_dd: u32,
    /// LINKAGE: BILL-315-DATA
    pub bill_315_data: Bill315Data,
    /// LINKAGE: PROV-TABLE
    pub prov_table: ProvTable,
    /// LINKAGE: PROV-DATA-2
    pub prov_data_2: ProvData2,
    /// LINKAGE: PROV-DATA-3
    pub prov_data_3: ProvData3,
    /// LINKAGE: MSA-WI-TABLE
    pub msa_wi_table: MsaWiTable,
    /// LINKAGE: CBSA-WI-TABLE
    pub cbsa_wi_table: CbsaWiTable,
    /// INDEXED BY PD2
    pub pd2: u32,
    /// INDEXED BY PD3
    pub pd3: u32,
    /// INDEXED BY MU1
    pub mu1: u32,
    /// INDEXED BY CU1
    pub cu1: u32,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            w_storage_ref: FixedString::from_str("HOSDR210      - W O R K I N G   S T O R A G E"),
            hos_version: FixedString::from_str("HOSDR210"),
            hosop210: FixedString::from_str("HOSOP210"),
            hospr210: FixedString::from_str("HOSPR210"),
            eof_msa_sw: 0u32,
            eof_cbsa_sw: 0u32,
            eof_bill_sw: 0u32,
            eof_prov_sw: 0u32,
            bill_ctr: 0u32,
            rate_ctr: 0u32,
            prov_ctr: 0u32,
            search_msa_lugar: Default::default(),
            search_msa: Default::default(),
            search_msa_pos12: Default::default(),
            search_msa_pos34: Default::default(),
            search_lugar: Default::default(),
            search_cbsa: Default::default(),
            search_cbsa_pos123: Default::default(),
            search_cbsa_pos45: Default::default(),
            ut1_stat: Default::default(),
            ut1_stat1: Default::default(),
            ut1_stat2: Default::default(),
            ut2_stat: Default::default(),
            ut2_stat1: Default::default(),
            ut2_stat2: Default::default(),
            ut3_stat: Default::default(),
            ut3_stat1: Default::default(),
            ut3_stat2: Default::default(),
            ut4_stat: Default::default(),
            ut4_stat1: Default::default(),
            ut4_stat2: Default::default(),
            ut5_stat: Default::default(),
            ut5_stat1: Default::default(),
            ut5_stat2: Default::default(),
            prov_new_hold: Default::default(),
            prov_newrec_hold1: Default::default(),
            p_new_npi10: Default::default(),
            p_new_npi8: Default::default(),
            p_new_npi_filler: Default::default(),
            p_new_provider_no: Default::default(),
            p_new_state: Default::default(),
            p_new_date_data: Default::default(),
            p_new_eff_date: Default::default(),
            p_new_eff_dt_cc: Default::default(),
            p_new_eff_dt_yy: Default::default(),
            p_new_eff_dt_mm: Default::default(),
            p_new_eff_dt_dd: Default::default(),
            p_new_fy_begin_date: Default::default(),
            p_new_fy_beg_dt_cc: Default::default(),
            p_new_fy_beg_dt_yy: Default::default(),
            p_new_fy_beg_dt_mm: Default::default(),
            p_new_fy_beg_dt_dd: Default::default(),
            p_new_report_date: Default::default(),
            p_new_report_dt_cc: Default::default(),
            p_new_report_dt_yy: Default::default(),
            p_new_report_dt_mm: Default::default(),
            p_new_report_dt_dd: Default::default(),
            p_new_termination_date: Default::default(),
            p_new_term_dt_cc: Default::default(),
            p_new_term_dt_yy: Default::default(),
            p_new_term_dt_mm: Default::default(),
            p_new_term_dt_dd: Default::default(),
            p_new_waiver_code: Default::default(),
            p_new_inter_no: Default::default(),
            p_new_provider_type: Default::default(),
            p_new_current_census_div: Default::default(),
            p_new_msa_data: Default::default(),
            p_new_chg_code_index: Default::default(),
            p_new_geo_loc_msax: Default::default(),
            p_new_wage_index_loc_msa: Default::default(),
            p_new_stand_amt_loc_msa: Default::default(),
            p_new_sol_com_dep_hosp_yr: Default::default(),
            p_new_lugar: Default::default(),
            p_new_temp_relief_ind: Default::default(),
            p_new_fed_pps_blend_ind: Default::default(),
            prov_newrec_hold2: Default::default(),
            p_new_variables: Default::default(),
            p_new_fac_spec_rate: Default::default(),
            p_new_cola: Default::default(),
            p_new_intern_ratio: Default::default(),
            p_new_bed_size: Default::default(),
            p_new_oper_cstchg_ratio: Default::default(),
            p_new_cmi: Default::default(),
            p_new_ssi_ratio: Default::default(),
            p_new_medicaid_ratio: Default::default(),
            p_new_pps_blend_yr_ind: Default::default(),
            p_new_prup_update_factor: Default::default(),
            p_new_dsh_percent: Default::default(),
            p_new_fye_date: Default::default(),
            p_new_cbsa_data: Default::default(),
            w_p_new_cbsa_spec_pay_ind: Default::default(),
            w_p_new_cbsa_hosp_qual_ind: Default::default(),
            w_p_new_cbsa_geo_loc: Default::default(),
            w_p_new_cbsa_reclass_loc: Default::default(),
            w_p_new_cbsa_stand_amt_loc: Default::default(),
            w_p_new_cbsa_spec_wage_index: Default::default(),
            prov_newrec_hold3: Default::default(),
            p_new_pass_amt_data: Default::default(),
            p_new_pass_amt_capital: Default::default(),
            p_new_pass_amt_dir_med_ed: Default::default(),
            p_new_pass_amt_organ_acq: Default::default(),
            p_new_pass_amt_plus_misc: Default::default(),
            p_new_capi_data: Default::default(),
            p_new_capi_pps_pay_code: Default::default(),
            p_new_capi_hosp_spec_rate: Default::default(),
            p_new_capi_old_harm_rate: Default::default(),
            p_new_capi_new_harm_ratio: Default::default(),
            p_new_capi_cstchg_ratio: Default::default(),
            p_new_capi_new_hosp: Default::default(),
            p_new_capi_ime: Default::default(),
            p_new_capi_exceptions: Default::default(),
            p_val_based_purch_score: Default::default(),
            w_fy_begin_date: Default::default(),
            w_fy_begin_cc: Default::default(),
            w_fy_begin_yy: Default::default(),
            w_fy_begin_mm: Default::default(),
            w_fy_begin_dd: Default::default(),
            w_fy_end_date: Default::default(),
            w_fy_end_cc: Default::default(),
            w_fy_end_yy: Default::default(),
            w_fy_end_mm: Default::default(),
            w_fy_end_dd: Default::default(),
            bill_315_data: Default::default(),
            prov_table: Default::default(),
            prov_data_2: Default::default(),
            prov_data_3: Default::default(),
            msa_wi_table: Default::default(),
            cbsa_wi_table: Default::default(),
            pd2: 1,
            pd3: 1,
            mu1: 1,
            cu1: 1,
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// CBSA-WI-TABLE
fn p_cbsa_wi_table(state: &mut ProgramState) {
    p_0200_process_records(state);
    p_0200_exit(state);
    return;
}

/// 0200-PROCESS-RECORDS
fn p_0200_process_records(state: &mut ProgramState) {
    state.bill_315_data.bill_returned_data = Default::default();
    state.bill_315_data.bill_group1.bill_pay_amt1 = Decimal::from(0i64);
    state.bill_315_data.bill_group2.bill_pay_amt2 = Decimal::from(0i64);
    state.bill_315_data.bill_group3.bill_pay_amt3 = Decimal::from(0i64);
    state.bill_315_data.bill_group4.bill_pay_amt4 = Decimal::from(0i64);
    state.bill_315_data.bill_sia_add_on_pymts = Default::default();
    state.w_fy_begin_date.w_fy_begin_cc = Default::default();
    state.w_fy_begin_date.w_fy_begin_yy = Default::default();
    state.w_fy_end_date.w_fy_end_cc = Default::default();
    state.w_fy_end_date.w_fy_end_yy = Default::default();
    state.w_fy_begin_date.w_fy_begin_cc = state.bill_315_data.bill_from_date.bill_from_cc as u32;
    state.w_fy_end_date.w_fy_end_cc = state.bill_315_data.bill_from_date.bill_from_cc as u32;
    if (state.bill_315_data.bill_from_date.bill_from_mm >= 1) && (state.bill_315_data.bill_from_date.bill_from_mm <= 9) {
        state.w_fy_begin_date.w_fy_begin_yy = (state.bill_315_data.bill_from_date.bill_from_yy as i64 - 1 as i64) as u32;
        // SKIP: unresolved ref
    } else {
        state.w_fy_begin_date.w_fy_begin_yy = state.bill_315_data.bill_from_date.bill_from_yy as u32;
        state.w_fy_end_date.w_fy_end_yy = (state.bill_315_data.bill_from_date.bill_from_yy as i64 + 1 as i64) as u32;
    }
    if state.eof_bill_sw == 0 {
        state.bill_ctr += 1 as u32;
        p_0300_process_data(state);
        p_0300_exit(state);
    }
}

/// 0200-EXIT
fn p_0200_exit(state: &mut ProgramState) {
}

/// 0300-PROCESS-DATA
fn p_0300_process_data(state: &mut ProgramState) {
    p_0700_get_provider(state);
    p_0700_exit(state);
    if state.bill_315_data.bill_returned_data.bill_rtc.trimmed() != "00" {
        p_0300_exit(state); return;
        if ({ let _s = format!("{}", state.prov_new_hold.prov_newrec_hold1.p_new_date_data.p_new_eff_date); _s.trim().to_string() } < "20051001".to_string()) && ({ let _s = format!("{}", state.bill_315_data.bill_from_date); _s.trim().to_string() } > "20050930".to_string()) {
            state.bill_315_data.bill_returned_data.bill_rtc = FixedString::from_str("51");
            p_0300_exit(state); return;
            if { let _s = format!("{}", state.bill_315_data.bill_from_date); _s.trim().to_string() } > "20050930".to_string() {
                p_0375_get_cbsa(state);
                p_0375_exit(state);
            } else {
                p_0350_get_msa(state);
                p_0350_exit(state);
            }
        }
    }
}

/// 0300-EXIT
fn p_0300_exit(state: &mut ProgramState) {
}

/// 0350-GET-MSA
fn p_0350_get_msa(state: &mut ProgramState) {
    if state.prov_new_hold.prov_newrec_hold1.p_new_msa_data.p_new_geo_loc_msax_rur.p_new_rural1 == "  " {
        state.search_msa_lugar.search_msa.search_msa_pos12 = "99".parse::<u32>().unwrap_or(0);
        state.search_msa_lugar.search_msa.search_msa_pos34 = state.prov_new_hold.prov_newrec_hold1.p_new_msa_data.p_new_geo_loc_msax_rur.p_new_geo_rural2.trimmed().parse::<u32>().unwrap_or(0);
    } else {
        state.search_msa_lugar.search_msa = Default::default();
        if { let _s = format!("{}", state.bill_315_data.bill_from_date); _s.trim().to_string() } < "19991001".to_string() {
            state.search_msa_lugar.search_lugar = FixedString::copy_from(&state.prov_new_hold.prov_newrec_hold1.p_new_lugar);
        } else {
            state.search_msa_lugar.search_lugar = FixedString::spaces();
            state.bill_315_data.bill_prov_msa_lugar.bill_prov_msa = FixedString::copy_from(&state.prov_new_hold.prov_newrec_hold1.p_new_msa_data.p_new_geo_loc_msax);
            if { let _s = format!("{}", state.bill_315_data.bill_from_date); _s.trim().to_string() } < "19991001".to_string() {
                state.bill_315_data.bill_prov_msa_lugar.bill_prov_lugar = FixedString::copy_from(&state.prov_new_hold.prov_newrec_hold1.p_new_lugar);
            } else {
                state.bill_315_data.bill_prov_msa_lugar.bill_prov_lugar = FixedString::spaces();
                if { let _s = format!("{}", state.bill_315_data.bill_from_date); _s.trim().to_string() } < "19991001".to_string() {
                    state.search_msa_lugar.search_lugar = FixedString::copy_from(&state.prov_new_hold.prov_newrec_hold1.p_new_lugar);
                } else {
                    state.search_msa_lugar.search_lugar = FixedString::spaces();
                    state.bill_315_data.bill_prov_msa_lugar.bill_prov_msa = FixedString::copy_from(&state.prov_new_hold.prov_newrec_hold1.p_new_msa_data.p_new_geo_loc_msax);
                    if { let _s = format!("{}", state.bill_315_data.bill_from_date); _s.trim().to_string() } < "19991001".to_string() {
                        state.bill_315_data.bill_prov_msa_lugar.bill_prov_lugar = FixedString::copy_from(&state.prov_new_hold.prov_newrec_hold1.p_new_lugar);
                    } else {
                        state.bill_315_data.bill_prov_msa_lugar.bill_prov_lugar = FixedString::spaces();
                        p_0400_search_4_msa(state);
                        p_0400_search_exit(state);
                        if state.bill_315_data.bill_returned_data.bill_rtc.trimmed() == "00" {
                            p_0500_get_hosp_wage_index(state);
                            p_0500_exit(state);
                        }
                    }
                }
            }
        }
    }
    state.bill_315_data.bill_prov_wage_index = (0).into();
    state.bill_315_data.bill_bene_wage_index = (0).into();
    p_0350_exit(state); return;
    // SKIP: unresolved condition
    state.bill_315_data.bill_returned_data.bill_rtc = "40".into();
    p_0350_exit(state); return;
    {
        let _bytes = state.bill_315_data.bill_bene_msa_lugar.bill_bene_msa.as_bytes();
        let _len = _bytes.len();
        if _len > 0 { let _end = _len.min(0+2); let _s = String::from_utf8_lossy(&_bytes[0.._end]).trim().to_string(); state.search_msa_lugar.search_msa.search_msa_pos12 = _s.parse().unwrap_or_default(); }
        if _len > 2 { let _end = _len.min(2+2); let _s = String::from_utf8_lossy(&_bytes[2.._end]).trim().to_string(); state.search_msa_lugar.search_msa.search_msa_pos34 = _s.parse().unwrap_or_default(); }
    }
    if { let _s = format!("{}", state.bill_315_data.bill_from_date); _s.trim().to_string() } < "19991001".to_string() {
        state.search_msa_lugar.search_lugar = FixedString::copy_from(&state.bill_315_data.bill_bene_msa_lugar.bill_bene_lugar);
    } else {
        state.search_msa_lugar.search_lugar = FixedString::spaces();
        p_0400_search_4_msa(state);
        p_0400_search_exit(state);
        if state.bill_315_data.bill_returned_data.bill_rtc.trimmed() == "00" {
            p_0550_get_bene_wage_index(state);
            p_0550_exit(state);
        }
    }
    state.bill_315_data.bill_prov_wage_index = (0).into();
    state.bill_315_data.bill_bene_wage_index = (0).into();
    p_0350_exit(state); return;
    // SKIP: unresolved condition
    state.bill_315_data.bill_returned_data.bill_rtc = "50".into();
    p_0350_exit(state); return;
}

/// 0350-EXIT
fn p_0350_exit(state: &mut ProgramState) {
}

/// 0375-GET-CBSA
fn p_0375_get_cbsa(state: &mut ProgramState) {
    if { let _s = format!("{}", state.bill_315_data.bill_from_date); _s.trim().to_string() } < "20080101".to_string() {
        if state.prov_new_hold.prov_newrec_hold2.p_new_cbsa_data.w_p_new_cbsa_geo_rural.w_p_new_cbsa_geo_rural1st == "   " {
            state.search_cbsa.search_cbsa_pos123 = "999".parse::<u32>().unwrap_or(0);
            state.search_cbsa.search_cbsa_pos45 = state.prov_new_hold.prov_newrec_hold2.p_new_cbsa_data.w_p_new_cbsa_geo_rural.w_p_new_cbsa_geo_rural2nd.trimmed().parse::<u32>().unwrap_or(0);
        } else {
            {
                let _bytes = state.prov_new_hold.prov_newrec_hold2.p_new_cbsa_data.w_p_new_cbsa_geo_loc.as_bytes();
                let _len = _bytes.len();
                if _len > 0 { let _end = _len.min(0+3); let _s = String::from_utf8_lossy(&_bytes[0.._end]).trim().to_string(); state.search_cbsa.search_cbsa_pos123 = _s.parse().unwrap_or_default(); }
                if _len > 3 { let _end = _len.min(3+2); let _s = String::from_utf8_lossy(&_bytes[3.._end]).trim().to_string(); state.search_cbsa.search_cbsa_pos45 = _s.parse().unwrap_or_default(); }
            }
            state.bill_315_data.bill_prov_cbsa = FixedString::copy_from(&state.prov_new_hold.prov_newrec_hold2.p_new_cbsa_data.w_p_new_cbsa_geo_loc);
        }
    } else {
        {
            let _bytes = state.bill_315_data.bill_prov_cbsa.as_bytes();
            let _len = _bytes.len();
            if _len > 0 { let _end = _len.min(0+3); let _s = String::from_utf8_lossy(&_bytes[0.._end]).trim().to_string(); state.search_cbsa.search_cbsa_pos123 = _s.parse().unwrap_or_default(); }
            if _len > 3 { let _end = _len.min(3+2); let _s = String::from_utf8_lossy(&_bytes[3.._end]).trim().to_string(); state.search_cbsa.search_cbsa_pos45 = _s.parse().unwrap_or_default(); }
        }
        p_0450_search_4_cbsa(state);
        p_0450_search_exit(state);
        if state.bill_315_data.bill_returned_data.bill_rtc.trimmed() == "00" {
            p_0525_get_hosp_wage_index(state);
            p_0525_exit(state);
        }
    }
    state.bill_315_data.bill_prov_wage_index = (0).into();
    state.bill_315_data.bill_bene_wage_index = (0).into();
    p_0375_exit(state); return;
    // SKIP: unresolved condition
    state.bill_315_data.bill_returned_data.bill_rtc = "40".into();
    p_0375_exit(state); return;
    {
        let _bytes = state.bill_315_data.bill_bene_cbsa.as_bytes();
        let _len = _bytes.len();
        if _len > 0 { let _end = _len.min(0+3); let _s = String::from_utf8_lossy(&_bytes[0.._end]).trim().to_string(); state.search_cbsa.search_cbsa_pos123 = _s.parse().unwrap_or_default(); }
        if _len > 3 { let _end = _len.min(3+2); let _s = String::from_utf8_lossy(&_bytes[3.._end]).trim().to_string(); state.search_cbsa.search_cbsa_pos45 = _s.parse().unwrap_or_default(); }
    }
    p_0450_search_4_cbsa(state);
    p_0450_search_exit(state);
    if state.bill_315_data.bill_returned_data.bill_rtc.trimmed() == "00" {
        p_0575_get_bene_wage_index(state);
        p_0575_exit(state);
    }
    state.bill_315_data.bill_prov_wage_index = (0).into();
    state.bill_315_data.bill_bene_wage_index = (0).into();
    p_0375_exit(state); return;
    // SKIP: unresolved condition
    state.bill_315_data.bill_returned_data.bill_rtc = "50".into();
    p_0375_exit(state); return;
    p_1000_call(state);
    p_1000_exit(state);
}

/// 0375-EXIT
fn p_0375_exit(state: &mut ProgramState) {
}

/// 0400-SEARCH-4-MSA
fn p_0400_search_4_msa(state: &mut ProgramState) {
    state.mu1 = 1 as u32;
    // SKIP: unresolved ref
}

/// 0400-SEARCH-EXIT
fn p_0400_search_exit(state: &mut ProgramState) {
}

/// 0450-SEARCH-4-CBSA
fn p_0450_search_4_cbsa(state: &mut ProgramState) {
    state.cu1 = 1 as u32;
    // SKIP: unresolved ref
}

/// 0450-SEARCH-EXIT
fn p_0450_search_exit(state: &mut ProgramState) {
}

/// 0500-GET-HOSP-WAGE-INDEX
fn p_0500_get_hosp_wage_index(state: &mut ProgramState) {
    // SKIP: unresolved condition
}

/// 0500-EXIT
fn p_0500_exit(state: &mut ProgramState) {
}

/// 0525-GET-HOSP-WAGE-INDEX
fn p_0525_get_hosp_wage_index(state: &mut ProgramState) {
    // SKIP: unresolved condition
    // SKIP: unresolved ref: state.bill_315_data.bill_prov_wage_index = Decimal::from_i64(state.cbsa_wi_table.m_cbsa_data[((i64::from(state._unresolved_cu2 - 1)) as usize).min(8999)].m_cbsa_wage_ind.value, state.cbsa_wi_table.m_cbsa_data[((i64::from(state._unresolved_cu2 - 1)) as usize).min(8999)].m_cbsa_wage_ind.scale);
}

/// 0525-EXIT
fn p_0525_exit(state: &mut ProgramState) {
}

/// 0550-GET-BENE-WAGE-INDEX
fn p_0550_get_bene_wage_index(state: &mut ProgramState) {
    // SKIP: unresolved condition
}

/// 0550-EXIT
fn p_0550_exit(state: &mut ProgramState) {
}

/// 0575-GET-BENE-WAGE-INDEX
fn p_0575_get_bene_wage_index(state: &mut ProgramState) {
    // SKIP: unresolved condition
    // SKIP: unresolved ref: state.bill_315_data.bill_bene_wage_index = Decimal::from_i64(state.cbsa_wi_table.m_cbsa_data[((i64::from(state._unresolved_cu2 - 1)) as usize).min(8999)].m_cbsa_wage_ind.value, state.cbsa_wi_table.m_cbsa_data[((i64::from(state._unresolved_cu2 - 1)) as usize).min(8999)].m_cbsa_wage_ind.scale);
}

/// 0575-EXIT
fn p_0575_exit(state: &mut ProgramState) {
}

/// 0700-GET-PROVIDER
fn p_0700_get_provider(state: &mut ProgramState) {
    if state.bill_315_data.bill_prov_no.trimmed().to_string() != { let _s = format!("{}", state.prov_new_hold.prov_newrec_hold1.p_new_provider_no); _s.trim().to_string() } {
        // SKIP: unresolved ref: state._unresolved_px2 = 1;
        // SKIP: unresolved ref
    }
}

/// 0700-EXIT
fn p_0700_exit(state: &mut ProgramState) {
}

/// 0800-GET-CURR-PROV
fn p_0800_get_curr_prov(state: &mut ProgramState) {
    // SKIP: unresolved condition
}

/// 0800-EXIT
fn p_0800_exit(state: &mut ProgramState) {
}

/// 1000-CALL
fn p_1000_call(state: &mut ProgramState) {
    {
        let mut _p1 = (state.bill_315_data).clone();
        hospr210(&mut _p1);
        state.bill_315_data = _p1;
    }
}

/// 1000-EXIT
fn p_1000_exit(state: &mut ProgramState) {
}

// ── Runtime Stubs ──────────────────────────────────────────────

/// External: CALL 'HOSPR210'
fn hospr210(_param1: &mut impl std::fmt::Debug) {
    todo!("External subroutine 'HOSPR210' not yet linked — implement or link the HOSPR210 module")
}

fn main() {
    let mut state = ProgramState::default();
    p_cbsa_wi_table(&mut state);
}

