// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.


use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone, Default, PartialEq)]
pub struct HoldSnfCbsa {
    /// HOLD-SNF-CBSA-1ST
    pub hold_snf_cbsa_1st: FixedString<3>,
    /// HOLD-SNF-CBSA-2ND
    pub hold_snf_cbsa_2nd: FixedString<2>,
}
impl std::fmt::Display for HoldSnfCbsa {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.hold_snf_cbsa_1st, self.hold_snf_cbsa_2nd)
    }
}
impl From<&str> for HoldSnfCbsa {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for HoldSnfCbsa {
    fn from(_s: String) -> Self { Self::default() }
}
impl HoldSnfCbsa {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CbsaWageIndexRecord {
    /// CBSA-WIR-CBSA
    pub cbsa_wir_cbsa: FixedString<5>,
    /// CBSA-WIR-EFFDATE
    pub cbsa_wir_effdate: FixedString<8>,
    /// CBSA-WIR-AREA-WAGEIND
    pub cbsa_wir_area_wageind: Decimal /* 2,4 Unsigned */,
}
impl std::fmt::Display for CbsaWageIndexRecord {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.cbsa_wir_cbsa, self.cbsa_wir_effdate, self.cbsa_wir_area_wageind)
    }
}
impl From<&str> for CbsaWageIndexRecord {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CbsaWageIndexRecord {
    fn from(_s: String) -> Self { Self::default() }
}
impl CbsaWageIndexRecord {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SnfData {
    /// SNF-INPUT-DATA
    pub snf_input_data: SnfInputData,
}
impl std::fmt::Display for SnfData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.snf_input_data)
    }
}
impl From<&str> for SnfData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for SnfData {
    fn from(_s: String) -> Self { Self::default() }
}
impl SnfData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SnfInputData {
    /// SNF-MSA
    pub snf_msa: FixedString<4>,
    /// SNF-CBSA
    pub snf_cbsa: SnfCbsa,
    /// SNF-SPEC-WI-IND
    pub snf_spec_wi_ind: FixedString<1>,
    /// SNF-SPEC-WI
    pub snf_spec_wi: Decimal /* 2,4 Unsigned */,
    /// SNF-SPEC-WI-X
    pub snf_spec_wi_x: FixedString<6>,
    /// SNF-HIPPS-CODE
    pub snf_hipps_code: FixedString<5>,
    /// SNF-FROM-DATE
    pub snf_from_date: SnfFromDate,
    /// SNF-THRU-DATE
    pub snf_thru_date: SnfThruDate,
    /// SNF-FED-BLEND
    pub snf_fed_blend: FixedString<1>,
    /// SNF-FACILITY-RATE
    pub snf_facility_rate: Decimal /* 5,2 Unsigned */,
    /// SNF-DIAGNOSIS-CODES
    pub snf_diagnosis_codes: SnfDiagnosisCodes,
    /// SNF-PAY-RTC
    pub snf_pay_rtc: SnfPayRtc,
    /// VBP-DATA
    pub vbp_data: VbpData,
    /// PDPM-DATA
    pub pdpm_data: PdpmData,
    /// SNF-SUPP-WI-DATA
    pub snf_supp_wi_data: SnfSuppWiData,
    /// FILLER PIC FILLER
    pub _filler_242: FixedString<38>,
}
impl std::fmt::Display for SnfInputData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self.snf_msa, self.snf_cbsa, self.snf_spec_wi_ind, self.snf_spec_wi, self.snf_spec_wi_x, self.snf_hipps_code, self.snf_from_date, self.snf_thru_date, self.snf_fed_blend, self.snf_facility_rate, self.snf_diagnosis_codes, self.snf_pay_rtc, self.vbp_data, self.pdpm_data, self.snf_supp_wi_data, self._filler_242)
    }
}
impl From<&str> for SnfInputData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for SnfInputData {
    fn from(_s: String) -> Self { Self::default() }
}
impl SnfInputData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SnfCbsa {
    /// SNF-CBSA-1ST
    pub snf_cbsa_1st: FixedString<3>,
    /// SNF-CBSA-2ND
    pub snf_cbsa_2nd: FixedString<2>,
}
impl std::fmt::Display for SnfCbsa {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.snf_cbsa_1st, self.snf_cbsa_2nd)
    }
}
impl From<&str> for SnfCbsa {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for SnfCbsa {
    fn from(_s: String) -> Self { Self::default() }
}
impl SnfCbsa {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SnfFromDate {
    /// SNF-FROM-CC
    pub snf_from_cc: FixedString<2>,
    /// SNF-FROM-YYMMDD
    pub snf_from_yymmdd: SnfFromYymmdd,
}
impl std::fmt::Display for SnfFromDate {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.snf_from_cc, self.snf_from_yymmdd)
    }
}
impl From<&str> for SnfFromDate {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for SnfFromDate {
    fn from(_s: String) -> Self { Self::default() }
}
impl SnfFromDate {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SnfFromYymmdd {
    /// SNF-FROM-YY
    pub snf_from_yy: FixedString<2>,
    /// SNF-FROM-MM
    pub snf_from_mm: FixedString<2>,
    /// SNF-FROM-DD
    pub snf_from_dd: FixedString<2>,
}
impl std::fmt::Display for SnfFromYymmdd {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.snf_from_yy, self.snf_from_mm, self.snf_from_dd)
    }
}
impl From<&str> for SnfFromYymmdd {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for SnfFromYymmdd {
    fn from(_s: String) -> Self { Self::default() }
}
impl SnfFromYymmdd {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SnfThruDate {
    /// SNF-THRU-CC
    pub snf_thru_cc: FixedString<2>,
    /// SNF-THRU-YYMMDD
    pub snf_thru_yymmdd: SnfThruYymmdd,
}
impl std::fmt::Display for SnfThruDate {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.snf_thru_cc, self.snf_thru_yymmdd)
    }
}
impl From<&str> for SnfThruDate {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for SnfThruDate {
    fn from(_s: String) -> Self { Self::default() }
}
impl SnfThruDate {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SnfThruYymmdd {
    /// SNF-THRU-YY
    pub snf_thru_yy: FixedString<2>,
    /// SNF-THRU-MM
    pub snf_thru_mm: FixedString<2>,
    /// SNF-THRU-DD
    pub snf_thru_dd: FixedString<2>,
}
impl std::fmt::Display for SnfThruYymmdd {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.snf_thru_yy, self.snf_thru_mm, self.snf_thru_dd)
    }
}
impl From<&str> for SnfThruYymmdd {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for SnfThruYymmdd {
    fn from(_s: String) -> Self { Self::default() }
}
impl SnfThruYymmdd {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SnfDiagnosisCodes {
    /// SNF-PRIN-DIAG-CODE
    pub snf_prin_diag_code: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE2
    pub snf_other_diag_code2: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE3
    pub snf_other_diag_code3: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE4
    pub snf_other_diag_code4: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE5
    pub snf_other_diag_code5: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE6
    pub snf_other_diag_code6: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE7
    pub snf_other_diag_code7: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE8
    pub snf_other_diag_code8: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE9
    pub snf_other_diag_code9: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE10
    pub snf_other_diag_code10: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE11
    pub snf_other_diag_code11: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE12
    pub snf_other_diag_code12: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE13
    pub snf_other_diag_code13: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE14
    pub snf_other_diag_code14: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE15
    pub snf_other_diag_code15: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE16
    pub snf_other_diag_code16: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE17
    pub snf_other_diag_code17: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE18
    pub snf_other_diag_code18: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE19
    pub snf_other_diag_code19: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE20
    pub snf_other_diag_code20: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE21
    pub snf_other_diag_code21: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE22
    pub snf_other_diag_code22: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE23
    pub snf_other_diag_code23: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE24
    pub snf_other_diag_code24: FixedString<7>,
    /// SNF-OTHER-DIAG-CODE25
    pub snf_other_diag_code25: FixedString<7>,
}
impl std::fmt::Display for SnfDiagnosisCodes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self.snf_prin_diag_code, self.snf_other_diag_code2, self.snf_other_diag_code3, self.snf_other_diag_code4, self.snf_other_diag_code5, self.snf_other_diag_code6, self.snf_other_diag_code7, self.snf_other_diag_code8, self.snf_other_diag_code9, self.snf_other_diag_code10, self.snf_other_diag_code11, self.snf_other_diag_code12, self.snf_other_diag_code13, self.snf_other_diag_code14, self.snf_other_diag_code15, self.snf_other_diag_code16, self.snf_other_diag_code17, self.snf_other_diag_code18, self.snf_other_diag_code19, self.snf_other_diag_code20, self.snf_other_diag_code21, self.snf_other_diag_code22, self.snf_other_diag_code23, self.snf_other_diag_code24, self.snf_other_diag_code25)
    }
}
impl From<&str> for SnfDiagnosisCodes {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for SnfDiagnosisCodes {
    fn from(_s: String) -> Self { Self::default() }
}
impl SnfDiagnosisCodes {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SnfPayRtc {
    /// SNF-PAYMENT-RATE
    pub snf_payment_rate: Decimal /* 6,2 Unsigned */,
    /// SNF-RTC
    pub snf_rtc: u32,
}
impl std::fmt::Display for SnfPayRtc {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.snf_payment_rate, self.snf_rtc)
    }
}
impl From<&str> for SnfPayRtc {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for SnfPayRtc {
    fn from(_s: String) -> Self { Self::default() }
}
impl SnfPayRtc {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct VbpData {
    /// VBP-MULTIPLIER
    pub vbp_multiplier: Decimal /* 1,11 Signed */,
    /// VBP-PAY-DIFF
    pub vbp_pay_diff: Decimal /* 6,2 Signed */,
}
impl std::fmt::Display for VbpData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.vbp_multiplier, self.vbp_pay_diff)
    }
}
impl From<&str> for VbpData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for VbpData {
    fn from(_s: String) -> Self { Self::default() }
}
impl VbpData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PdpmData {
    /// SNF-PDPM-UNITS
    pub snf_pdpm_units: u32,
    /// SNF-PDPM-PRIOR-DAYS
    pub snf_pdpm_prior_days: u32,
}
impl std::fmt::Display for PdpmData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.snf_pdpm_units, self.snf_pdpm_prior_days)
    }
}
impl From<&str> for PdpmData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PdpmData {
    fn from(_s: String) -> Self { Self::default() }
}
impl PdpmData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SnfSuppWiData {
    /// SNF-SUPP-WI-IND
    pub snf_supp_wi_ind: FixedString<1>,
    /// SNF-SUPP-WI
    pub snf_supp_wi: Decimal /* 2,4 Unsigned */,
}
impl std::fmt::Display for SnfSuppWiData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.snf_supp_wi_ind, self.snf_supp_wi)
    }
}
impl From<&str> for SnfSuppWiData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for SnfSuppWiData {
    fn from(_s: String) -> Self { Self::default() }
}
impl SnfSuppWiData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct HoldVariables {
    /// HOLD-VAR-DATA
    pub hold_var_data: HoldVarData,
    /// SNFPR-VERSION
    pub snfpr_version: FixedString<9>,
}
impl std::fmt::Display for HoldVariables {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.hold_var_data, self.snfpr_version)
    }
}
impl From<&str> for HoldVariables {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for HoldVariables {
    fn from(_s: String) -> Self { Self::default() }
}
impl HoldVariables {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct HoldVarData {
    /// REGION-IND
    pub region_ind: FixedString<1>,
    /// QRP-IND
    pub qrp_ind: FixedString<1>,
    /// AIDS-ADD-ON-IND
    pub aids_add_on_ind: FixedString<1>,
    /// AREA-WAGE-INDEX
    pub area_wage_index: Decimal /* 1,4 Unsigned */,
    /// IP-RATE
    pub ip_rate: Decimal /* 3,2 Unsigned */,
    /// GS-RATE
    pub gs_rate: Decimal /* 2,2 Unsigned */,
}
impl std::fmt::Display for HoldVarData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}", self.region_ind, self.qrp_ind, self.aids_add_on_ind, self.area_wage_index, self.ip_rate, self.gs_rate)
    }
}
impl From<&str> for HoldVarData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for HoldVarData {
    fn from(_s: String) -> Self { Self::default() }
}
impl HoldVarData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, PartialEq)]
pub struct CbsaWiTable {
    /// T-CBSA-DATA
    pub t_cbsa_data: [TCbsaData; 8000],
}
impl Default for CbsaWiTable {
    fn default() -> Self {
        Self {
            t_cbsa_data: std::array::from_fn(|_| Default::default()),
        }
    }
}
impl std::fmt::Display for CbsaWiTable {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "")
    }
}
impl From<&str> for CbsaWiTable {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CbsaWiTable {
    fn from(_s: String) -> Self { Self::default() }
}
impl CbsaWiTable {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct TCbsaData {
    /// T-CBSA
    pub t_cbsa: FixedString<5>,
    /// T-CBSA-EFFDATE
    pub t_cbsa_effdate: FixedString<8>,
    /// T-CBSA-WAGEIND
    pub t_cbsa_wageind: Decimal /* 2,4 Unsigned */,
}
impl std::fmt::Display for TCbsaData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.t_cbsa, self.t_cbsa_effdate, self.t_cbsa_wageind)
    }
}
impl From<&str> for TCbsaData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for TCbsaData {
    fn from(_s: String) -> Self { Self::default() }
}
impl TCbsaData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// W-STORAGE-REF
    pub w_storage_ref: FixedString<49>,
    /// SNFDR-VERSION
    pub snfdr_version: FixedString<9>,
    /// SNFPR210
    pub snfpr210: FixedString<8>,
    /// SNFPR205
    pub snfpr205: FixedString<8>,
    /// WS-WI-PCT-DECREASE-FY2021
    pub ws_wi_pct_decrease_fy2021: Decimal /* 1,2 Signed */,
    /// WS-WI-PCT-ADJ-FY2021
    pub ws_wi_pct_adj_fy2021: Decimal /* 1,2 Unsigned */,
    /// HOLD-SNF-CBSA
    pub hold_snf_cbsa: HoldSnfCbsa,
    /// HOLD-SNF-CBSA-1ST
    pub hold_snf_cbsa_1st: FixedString<3>,
    /// HOLD-SNF-CBSA-2ND
    pub hold_snf_cbsa_2nd: FixedString<2>,
    /// CBSA-WAGE-INDEX-RECORD
    pub cbsa_wage_index_record: CbsaWageIndexRecord,
    /// CBSA-WIR-CBSA
    pub cbsa_wir_cbsa: FixedString<5>,
    /// CBSA-WIR-EFFDATE
    pub cbsa_wir_effdate: FixedString<8>,
    /// CBSA-WIR-AREA-WAGEIND
    pub cbsa_wir_area_wageind: Decimal /* 2,4 Unsigned */,
    /// LINKAGE: SNF-DATA
    pub snf_data: SnfData,
    /// LINKAGE: HOLD-VARIABLES
    pub hold_variables: HoldVariables,
    /// LINKAGE: CBSA-WI-TABLE
    pub cbsa_wi_table: CbsaWiTable,
    /// INDEXED BY MA1
    pub ma1: u32,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            w_storage_ref: FixedString::from_str("SNF D R I V E R   - W O R K I N G   S T O R A G E"),
            snfdr_version: FixedString::from_str("SNFDR21.0"),
            snfpr210: FixedString::from_str("SNFPR210"),
            snfpr205: FixedString::from_str("SNFPR205"),
            ws_wi_pct_decrease_fy2021: Decimal::from(-0.05f64),
            ws_wi_pct_adj_fy2021: Decimal::from(0.95f64),
            hold_snf_cbsa: Default::default(),
            hold_snf_cbsa_1st: Default::default(),
            hold_snf_cbsa_2nd: Default::default(),
            cbsa_wage_index_record: Default::default(),
            cbsa_wir_cbsa: Default::default(),
            cbsa_wir_effdate: Default::default(),
            cbsa_wir_area_wageind: Default::default(),
            snf_data: Default::default(),
            hold_variables: Default::default(),
            cbsa_wi_table: Default::default(),
            ma1: 1,
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// CBSA-WI-TABLE
fn p_cbsa_wi_table(state: &mut ProgramState) {
}

/// SECTION
fn p_section(state: &mut ProgramState) {
    p_0100_process_records(state);
    p_0100_exit(state);
    return;
}

/// 0100-PROCESS-RECORDS
fn p_0100_process_records(state: &mut ProgramState) {
    state.snf_data.snf_input_data.snf_pay_rtc = Default::default();
    state.cbsa_wage_index_record = Default::default();
    state.hold_variables.hold_var_data = Default::default();
    if { let _s = format!("{}", state.snf_data.snf_input_data.snf_thru_date); _s.trim().to_string() } < "19980701".to_string() {
        state.snf_data.snf_input_data.snf_pay_rtc.snf_rtc = "40".parse::<u32>().unwrap_or(0);
        p_0100_exit(state); return;
        {
            let mut _bytes = vec![b' '; 5];
            { let _src = state.snf_data.snf_input_data.snf_cbsa.snf_cbsa_1st.as_bytes(); let _end = (0+3).min(_bytes.len()); let _cl = _src.len().min(_end-0); _bytes[0..0+_cl].copy_from_slice(&_src[.._cl]); }
            { let _src = state.snf_data.snf_input_data.snf_cbsa.snf_cbsa_2nd.as_bytes(); let _end = (3+2).min(_bytes.len()); let _cl = _src.len().min(_end-3); _bytes[3..3+_cl].copy_from_slice(&_src[.._cl]); }
            let _len = _bytes.len();
            if _len > 0 { let _end = _len.min(0+3); state.hold_snf_cbsa.hold_snf_cbsa_1st = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            if _len > 3 { let _end = _len.min(3+2); state.hold_snf_cbsa.hold_snf_cbsa_2nd = FixedString::from(String::from_utf8_lossy(&_bytes[3.._end])); }
        }
        // SKIP: unresolved condition
    }
    // SKIP: unresolved condition
    p_1900_select_cbsa_wage_index(state);
    p_hold_snf_cbsa(state);
    p_1900_exit(state);
    if &format!("{}", state.snf_data.snf_input_data.snf_pay_rtc.snf_rtc) != "00" {
        p_0100_exit(state); return;
        if { let _s = format!("{}", state.snf_data.snf_input_data.snf_thru_date); _s.trim().to_string() } > "20200930".to_string() {
            {
                let mut _p1 = (state.snf_data).clone();
                let mut _p2 = (state.hold_variables).clone();
                let mut _p3 = (state.cbsa_wage_index_record).clone();
                snfpr210(&mut _p1, &mut _p2, &mut _p3);
                state.snf_data = _p1;
                state.hold_variables = _p2;
                state.cbsa_wage_index_record = _p3;
            }
        }
    }
    if ({ let _s = format!("{}", state.snf_data.snf_input_data.snf_thru_date); _s.trim().to_string() } > "20190930".to_string()) && ({ let _s = format!("{}", state.snf_data.snf_input_data.snf_thru_date); _s.trim().to_string() } < "20201001".to_string()) {
        {
            let mut _p1 = (state.snf_data).clone();
            let mut _p2 = (state.hold_variables).clone();
            let mut _p3 = (state.cbsa_wage_index_record).clone();
            snfpr205(&mut _p1, &mut _p2, &mut _p3);
            state.snf_data = _p1;
            state.hold_variables = _p2;
            state.cbsa_wage_index_record = _p3;
        }
    }
}

/// 0100-EXIT
fn p_0100_exit(state: &mut ProgramState) {
}

/// 1900-SELECT-CBSA-WAGE-INDEX
fn p_1900_select_cbsa_wage_index(state: &mut ProgramState) {
    if &format!("{}", state.snf_data.snf_input_data.snf_spec_wi_ind) == &"Y".to_string() {
        state.snf_data.snf_input_data.snf_spec_wi_ind = "1".into();
        if (&format!("{}", state.snf_data.snf_input_data.snf_spec_wi_ind) == &"1".to_string()) && (state.snf_data.snf_input_data.snf_spec_wi_x.trimmed() != "") {
        } else {
            state.snf_data.snf_input_data.snf_pay_rtc.snf_rtc = "30".parse::<u32>().unwrap_or(0);
            p_1900_exit(state); return;
            if (&format!("{}", state.snf_data.snf_input_data.snf_spec_wi_ind) == &"1".to_string()) && (state.snf_data.snf_input_data.snf_spec_wi_x.trimmed() != "") {
            }
        }
    }
    state.cbsa_wage_index_record.cbsa_wir_cbsa = FixedString::copy_from(&state.snf_data.snf_input_data.snf_cbsa);
    state.cbsa_wage_index_record.cbsa_wir_effdate = "20051001".into();
    state.cbsa_wage_index_record.cbsa_wir_area_wageind = Decimal::from_i64(state.snf_data.snf_input_data.snf_spec_wi.value, state.snf_data.snf_input_data.snf_spec_wi.scale);
    p_1900_exit(state); return;
    p_2000_read_cbsa_file(state);
    p_2000_exit(state);
    if &format!("{}", state.snf_data.snf_input_data.snf_pay_rtc.snf_rtc) != "00" {
        p_0100_exit(state); return;
        p_2010_select_current_wage_index(state);
        p_2010_exit(state);
    }
}

/// HOLD-SNF-CBSA
fn p_hold_snf_cbsa(state: &mut ProgramState) {
    if i64::from(state.cbsa_wage_index_record.cbsa_wir_area_wageind) <= 0i64 {
        state.snf_data.snf_input_data.snf_pay_rtc.snf_rtc = "30".parse::<u32>().unwrap_or(0);
        p_1900_exit(state); return;
    }
    // SKIP: unresolved condition
    state.snf_data.snf_input_data.snf_pay_rtc.snf_rtc = "30".parse::<u32>().unwrap_or(0);
    p_1900_exit(state); return;
    // SKIP: unresolved condition
}

/// 1900-EXIT
fn p_1900_exit(state: &mut ProgramState) {
}

/// 2000-READ-CBSA-FILE
fn p_2000_read_cbsa_file(state: &mut ProgramState) {
    state.ma1 = 1 as u32;
    // SKIP: unresolved ref
}

/// 2000-EXIT
fn p_2000_exit(state: &mut ProgramState) {
}

/// 2010-SELECT-CURRENT-WAGE-INDEX
fn p_2010_select_current_wage_index(state: &mut ProgramState) {
    // SKIP: unresolved condition
}

/// 2010-EXIT
fn p_2010_exit(state: &mut ProgramState) {
}

/// 2020-CAP-WAGE-INDEX-DECREASE
fn p_2020_cap_wage_index_decrease(state: &mut ProgramState) {
    // SKIP: unresolved condition
    state.cbsa_wage_index_record.cbsa_wir_area_wageind = Decimal::from(i64::from((state.snf_data.snf_input_data.snf_supp_wi_data.snf_supp_wi * state.ws_wi_pct_adj_fy2021)));
}

/// 2020-EXIT
fn p_2020_exit(state: &mut ProgramState) {
}

// ── Runtime Stubs ──────────────────────────────────────────────

/// External: CALL 'SNFPR210'
fn snfpr210(_param1: &mut impl std::fmt::Debug, _param2: &mut impl std::fmt::Debug, _param3: &mut impl std::fmt::Debug) {
    todo!("External subroutine 'SNFPR210' not yet linked — implement or link the SNFPR210 module")
}

/// External: CALL 'SNFPR205'
fn snfpr205(_param1: &mut impl std::fmt::Debug, _param2: &mut impl std::fmt::Debug, _param3: &mut impl std::fmt::Debug) {
    todo!("External subroutine 'SNFPR205' not yet linked — implement or link the SNFPR205 module")
}

fn main() {
    let mut state = ProgramState::default();
    p_cbsa_wi_table(&mut state);
}

